import { test, expect, type Page } from '@playwright/test';
const device='a'.repeat(43),id='b1400000-0000-4000-8000-000000000001',host='b1400000-0000-4000-8000-000000000007',record='b1400000-0000-4000-8000-000000000009';
const future=()=>new Date(Date.now()+8*3600000).toISOString();
async function fixture(page:Page,role?:string){
 const state={writes:[] as {path:string;headers:Record<string,string>;body:Record<string,unknown>}[],delay:0,status:200,malformed:false,unknown:false,slotConflict:false,badgeReads:0,checkout:false};
 await page.addInitScript(()=>{sessionStorage.setItem('brainserve.connect.access-token','private-staff-token');sessionStorage.setItem('brainserve.connect.refresh-token','private-staff-refresh');});
 page.on('pageerror', error => console.log('BROWSER_ERROR', error.message));
    await page.route('http://backend.invalid/**',async route=>{const req=route.request(),path=new URL(req.url()).pathname.replace('/api/v1','');
 if(req.method()==='POST'){
  const body=(req.postDataJSON()??{}) as Record<string,unknown>;state.writes.push({path,headers:req.headers(),body});if(state.delay)await new Promise(resolve=>setTimeout(resolve,state.delay));
  if(state.status!==200)return route.fulfill({status:state.status,json:{detail:'Private visitor and provider details'}});
  if(path==='/kiosk/session')return route.fulfill({json:state.malformed?{label:'Gate',expiresAt:'bad',resetSeconds:0}:{label:'Gate',expiresAt:future(),resetSeconds:60}});
  if(path==='/kiosk/intake')return route.fulfill({json:{accepted:true}});
  if(path==='/admin/kiosks')return route.fulfill({json:{id,label:body.label,expiresAt:future(),revokedAt:null,version:0,token:device}});
  if(path==='/appointments/groups')return route.fulfill(state.slotConflict?{status:409,json:{errorCode:'SLOT_ALREADY_BOOKED',detail:'The selected slot is no longer available'}}:state.unknown?{status:503,json:{detail:'Unconfirmed'}}:{json:{id,label:body.label,createdAt:new Date().toISOString(),members:[{appointmentId:id,referenceNumber:'BSA-S14A-ABCD',status:'PENDING_SECURITY_INTAKE'},{appointmentId:host,referenceNumber:'BSA-S14B-ABCD',status:'PENDING_SECURITY_INTAKE'}]}});
  return route.fulfill({json:{}});
 }
 if(['/auth/me','/profile/me'].includes(path))return route.fulfill({json:{userId:id,employeeId:null,email:'s14@example.invalid',fullName:'Staff',roles:[role],permissions:[],forcePasswordChange:false,departmentId:null,photoUrl:null}});
 if(path==='/auth/security')return route.fulfill({json:{mfaRequired:true,mfaEnrolled:true,mfaVerified:true,stepUpRequired:false}});
 if(path==='/dashboard/summary')return route.fulfill({json:{awaitingApproval:0,activeVisits:1,totalEmployees:0,activeEmployees:0,scope:'COMPANY',departmentId:null}});
 if(path==='/dashboard/cards')return route.fulfill({status:503,json:{detail:'Unavailable'}});
 if(['/appointments','/employees','/admin/staff-accounts'].includes(path))return route.fulfill({json:{content:[],number:0,size:20,totalElements:0,totalPages:0,last:true}});
 if(path==='/public/hosts')return route.fulfill({json:[{id:host,displayName:'HR Person',designation:'HR',departmentId:id,departmentName:'HR',category:'HR'}]});
 if(path.includes('available-slots'))return route.fulfill({json:[{start:new Date(Date.now()+86400000).toISOString(),end:new Date(Date.now()+88200000).toISOString(),officeTimeZone:'Asia/Kolkata'}]});
 if(path==='/reception/visitors-inside')return route.fulfill({json:[{id:record,appointmentId:id,visitorName:'Visitor Example',badgeNumber:'S14-BADGE',checkedInAt:new Date().toISOString(),checkedOutAt:null,processedBy:'s14'}]});
 if(path.startsWith('/reception/badges/')){state.badgeReads++;return route.fulfill(state.checkout?{status:409,json:{detail:'Checkout'}}:{json:{badgeNumber:'S14-BADGE',referenceNumber:'BSA-S14A-ABCD',visitorName:'Visitor Example',companyName:'Example Company',expiresAt:future(),qrCodeDataUrl:'data:image/png;base64,iVBORw0KGgo=',templateVersion:1}});}
 if(path.includes('unread'))return route.fulfill({json:{unreadCount:0}});if(path==='/realtime/stream')return route.fulfill({status:204});return route.fulfill({json:[]});
 });
 await page.goto(role?'/':'/kiosk');if(role)await expect(page.getByRole('navigation',{name:'Role workspace'})).toBeAttached();return state;
}
async function connect(page:Page){await expect(page.getByRole('button', { name: 'Connect device', exact: true })).toBeEnabled();
    await page.getByLabel('Device code').fill(device);await page.getByRole('button',{name:'Connect device',exact:true}).click();await expect(page.getByLabel('Scanned QR content')).toBeVisible();}
async function navigate(page:Page,label:string){const menu=page.getByRole('button',{name:'Open navigation',exact:true});if(await menu.isVisible())await menu.click();await page.getByRole('navigation',{name:'Role workspace'}).getByRole('button',{name:label,exact:true}).click();}
for(const width of [360,768,1440])test(`kiosk controls fit ${width}px`,async({page},info)=>{await page.setViewportSize({width,height:900});await fixture(page);await connect(page);await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(await page.locator('button').evaluateAll(nodes=>nodes.every(node=>node.getBoundingClientRect().height>=44))).toBe(true);await page.screenshot({path:info.outputPath(`kiosk-${width}.png`),fullPage:true});});
test('kiosk clears the tab staff session, excludes staff authority and never persists the device capability',async({page})=>{const state=await fixture(page);await connect(page);expect(await page.evaluate(()=>[sessionStorage.getItem('brainserve.connect.access-token'),sessionStorage.getItem('brainserve.connect.refresh-token')])).toEqual([null,null]);await page.getByLabel('Scanned QR content').fill('private-signed-pass');await page.getByRole('button',{name:'Request arrival'}).click();await expect(page.getByRole('status')).toContainText('Arrival request received');expect(state.writes).toHaveLength(2);for(const req of state.writes){expect(req.headers.authorization).toBeUndefined();expect(req.headers.cookie).toBeUndefined();expect(req.headers['x-kiosk-token']).toBe(device);}expect(await page.evaluate(()=>JSON.stringify({...localStorage,...sessionStorage}))).not.toContain(device);await expect(page.getByLabel('Scanned QR content')).toHaveValue('');await page.reload();await expect(page.getByLabel('Device code')).toBeVisible();});
test('double submit clears QR immediately and sends one request',async({page})=>{const state=await fixture(page);await connect(page);state.delay=400;await page.getByLabel('Scanned QR content').fill('private-pass');await page.getByRole('button',{name:'Request arrival'}).evaluate((button:HTMLButtonElement)=>{button.click();button.click();});await expect(page.getByLabel('Scanned QR content')).toHaveValue('');await expect(page.getByRole('button',{name:'Submitting…'})).toBeDisabled();await expect(page.getByRole('status')).toBeVisible();expect(state.writes.filter(req=>req.path==='/kiosk/intake')).toHaveLength(1);});
test('manual reset fences late responses',async({page})=>{const state=await fixture(page);await connect(page);state.delay=400;await page.getByLabel('Scanned QR content').fill('private-pass');await page.getByRole('button',{name:'Request arrival'}).click();await expect.poll(()=>state.writes.length).toBe(2);await page.getByRole('button',{name:'Start again'}).click();await page.waitForTimeout(550);await expect(page.getByRole('status')).toHaveCount(0);await expect(page.getByLabel('Scanned QR content')).toHaveValue('');await expect(page.getByRole('button',{name:'Request arrival'})).toBeEnabled();});
test('sixty second idle reset removes visitor content',async({page})=>{await page.clock.install();await fixture(page);await connect(page);await page.getByLabel('Scanned QR content').fill('private-pass');await page.clock.fastForward(60001);await expect(page.getByLabel('Scanned QR content')).toHaveValue('');});
test('revoked device disconnects without staff refresh',async({page})=>{const state=await fixture(page);await connect(page);state.status=401;await page.getByLabel('Scanned QR content').fill('private-pass');await page.getByRole('button',{name:'Request arrival'}).click();await expect(page.getByLabel('Device code')).toBeVisible();await expect(page.getByRole('alert')).toContainText('expired');expect(state.writes).toHaveLength(2);});
test('malformed sessions reject and unavailable intake redacts service detail',async({page})=>{const state=await fixture(page);state.malformed=true;await expect(page.getByRole('button', { name: 'Connect device', exact: true })).toBeEnabled();
    await page.getByLabel('Device code').fill(device);await page.getByRole('button',{name:'Connect device'}).click();await expect(page.getByRole('alert')).toContainText('could not be confirmed');state.malformed=false;await connect(page);state.status=503;await page.getByLabel('Scanned QR content').fill('private-pass');await page.getByRole('button',{name:'Request arrival'}).click();await expect(page.getByRole('alert')).toContainText('Ask Reception or Security');await expect(page.locator('body')).not.toContainText('Private visitor');});
test('administrator code appears once and clears on session expiry',async({page})=>{const state=await fixture(page,'ROLE_SYSTEM_ADMIN');await navigate(page,'Visitor devices');const panel=page.getByRole('region',{name:'Visitor devices'});await panel.getByLabel('Device label').fill('Reception tablet');await expect(panel.getByRole('button',{name:'Create device code'})).toBeEnabled();await panel.getByRole('button',{name:'Create device code'}).click();await expect(panel).toContainText(device);expect(state.writes).toHaveLength(1);expect(await page.evaluate(()=>JSON.stringify({...localStorage,...sessionStorage}))).not.toContain(device);await page.evaluate(()=>window.dispatchEvent(new Event('brainserve:auth-session-expired')));await expect(page.locator('body')).not.toContainText(device);});
test('unconfirmed group retries the exact locked request',async({page})=>{const state=await fixture(page,'ROLE_RECEPTIONIST');await navigate(page,'Visitors');const panel=page.getByRole('region',{name:'Group preregistration'});await panel.getByLabel('Group label').fill('Interview cohort');await panel.getByLabel('Group host').selectOption(host);await expect(panel.getByLabel('Group time')).not.toHaveValue('');await panel.getByLabel('Group purpose').fill('Interview');await panel.getByLabel('Group visitors').fill('First | first@example.invalid | 0000000000 | Test\nSecond | second@example.invalid | 0000000001 | Test');state.unknown=true;await panel.getByRole('button',{name:'Register group',exact:true}).click();await expect(panel.getByRole('alert')).toContainText('not confirmed');await expect(panel.getByLabel('Group visitors')).toBeDisabled();state.unknown=false;await panel.getByRole('button',{name:'Retry same group request'}).click();await expect(panel.getByRole('status')).toContainText('2 visitors registered');expect(state.writes[1].body).toEqual(state.writes[0].body);});
test('badge printing rechecks checkout and print CSS hides staff controls',async({page})=>{const state=await fixture(page,'ROLE_SECURITY');await navigate(page,'Visitors');const panel=page.getByRole('region',{name:'Arrival requests and badges'});await panel.getByLabel('Visitor badge').selectOption(record);await panel.getByRole('button',{name:'Prepare badge'}).click();await expect(panel.locator('[data-visitor-badge]')).toContainText('Example Company');await page.emulateMedia({media:'print'});await expect.poll(()=>page.locator('nav[aria-label="Role workspace"]').evaluate(node=>getComputedStyle(node).visibility)).toBe('hidden');expect(await page.locator('[data-visitor-badge]').evaluate(node=>getComputedStyle(node).visibility)).toBe('visible');await page.emulateMedia({media:'screen'});state.checkout=true;await panel.getByRole('button',{name:'Print badge'}).click();await expect(panel.getByRole('alert')).toContainText('could not be prepared');await expect(panel.locator('[data-visitor-badge]')).toHaveCount(0);expect(state.badgeReads).toBe(2);});

test('a definite slot conflict unlocks the group so Reception can choose another time',async({page})=>{const state=await fixture(page,'ROLE_RECEPTIONIST');await navigate(page,'Visitors');const panel=page.getByRole('region',{name:'Group preregistration'});await panel.getByLabel('Group label').fill('Cohort');await panel.getByLabel('Group host').selectOption(host);await expect(panel.getByLabel('Group time')).not.toHaveValue('');await panel.getByLabel('Group purpose').fill('Interview');await panel.getByLabel('Group visitors').fill('First | first@example.invalid | 0000000000 | Test\nSecond | second@example.invalid | 0000000001 | Test');state.slotConflict=true;await panel.getByRole('button',{name:'Register group',exact:true}).click();await expect(panel.getByRole('alert')).toContainText('slot is no longer available');await expect(panel.getByLabel('Group visitors')).toBeEnabled();await expect(panel.getByLabel('Group time')).toHaveValue('');await expect(panel.getByRole('button',{name:'Register group',exact:true})).toBeDisabled();expect(state.writes).toHaveLength(1);});
