import { expect, test, type Page } from '@playwright/test';
import type { HandoverView, WorkMetric, WorkSummary } from '../features/work-planning/types';
import type { WorkboardItem } from '../features/workboard/types/workboard';
const departmentId = '11111111-1111-4111-8111-111111111111', employeeId = '22222222-2222-4222-8222-222222222222', targetId = '33333333-3333-4333-8333-333333333333', userId = '44444444-4444-4444-8444-444444444444', taskId = '55555555-5555-4555-8555-555555555555', leadId = '66666666-6666-4666-8666-666666666666';
const now = '2026-10-04T04:00:00Z';
const titles = ['Tasks assigned', 'Completed delivery', 'Overdue execution delivery', 'Pending delivery review', 'Submitted delivery', 'Final closures', 'Original commitment acceptance', 'Delivery cycle time', 'Rework rate', 'Active blockers', 'Stage wait time', 'Effort coverage', 'Final audit approvals'];
const cards: WorkMetric[] = titles.map((title, index) => ({ id: `WORK${String(index + 1).padStart(2, '0')}`, title, kind: index === 6 ? 'RATE' : 'COUNT', unit: index === 6 ? 'PERCENT' : 'TASKS', value: index === 6 ? 50 : index === 11 ? null : 2, numerator: index === 6 ? 1 : null, denominator: index === 6 ? 2 : null, sampleCount: 2, coverageKnown: 1, coverageTotal: 2, excluded: 1, smallSample: true, definition: index === 6 ? 'Current valid delivery acceptance by the immutable original office cutoff; unfinished and late tasks remain in the denominator.' : `Retained and authorized definition for WORK${index + 1}.`, reason: index === 11 ? 'Maintained estimates are incomplete.' : null }));
const task: WorkboardItem = { id: taskId, departmentId, employeeId, teamLeadUserId: userId, assignedByUserId: userId, assignedByRole: 'TEAM_LEAD', assigneeRole: 'EMPLOYEE', title: 'Retained office report', description: 'Review the office report and record its evidence.', departmentBranch: 'Engineering', dueDate: '2026-10-04', status: 'COMPLETED', employeeUpdate: 'Original authored report update.', teamLeadReview: null, startedAt: now, completedAt: now, approvedAt: null, acknowledgedAt: null, createdAt: now, version: 3, assigneeName: 'Original Worker', auditStatus: 'NOT_AUDITED', auditRecordId: null, auditVersion: null, updatedAt: now, submissionVersion: 1, priority: 'NORMAL', blocked: false, allowedActions: ['approve', 'request-changes'], nextActor: 'TEAM_LEAD', lane: 'REVIEW' };
async function fixture(page: Page, role: 'TEAM_LEAD' | 'CEO' = 'TEAM_LEAD') {
    const state = { requests: [] as string[], writes: [] as Record<string, unknown>[], contextError: false, summaryError: false, emptyRecords: false, recordsDenied: false, exportOversize: false, handoverConflict: false, handoverUnknown: false, handoverDelay: false,
        task: { ...task }, view: { taskId, taskVersion: 3, currentEmployeeId: employeeId, originalEmployeeId: employeeId, currentAssigneeName: 'Original Worker', originalAssigneeName: 'Original Worker', canHandover: true, unavailableReason: null, eligibleAssignees: [{ employeeId: targetId, displayName: 'New Worker', role: 'EMPLOYEE' }], history: [], historyTruncated: false } as HandoverView };
    const scope = role === 'CEO' ? 'COMPANY' : 'DEPARTMENT', profile = { userId, employeeId: leadId, email: 'sprint9@example.invalid', fullName: 'Planning Owner', roles: [`ROLE_${role}`], permissions: ['WORK_TASK_CREATE', 'WORK_INSIGHT_READ', 'REPORT_VIEW'], forcePasswordChange: false, departmentId, photoUrl: null };
    const department = { id: departmentId, code: 'ENG', name: 'Engineering', active: true, version: 1 }, springPage = (content: unknown[]) => ({ content, number: 0, size: 50, totalElements: content.length, totalPages: 1, last: true });
    const currentPlanning = () => ({ taskId, taskVersion: state.task.version, priority: 'NORMAL', originalDueDate: '2026-10-04', originalDueDateKnown: true, dueDate: '2026-10-04', estimateMinutes: null, evidenceRequired: false, checklist: [], blockers: [], evidence: [], contactOptions: [], permissions: { manage: false, progress: false, blocker: false, resolveBlocker: false, upload: false }, retainedDrafts: [], submissions: [{ version: 1, authorEmployeeId: employeeId, authorUserId: userId, authorName: 'Original Worker', assignmentRevision: 0, authorshipKnown: true, employeeUpdate: 'Original authored report update.', submittedAt: now, acceptedAt: now, acceptedByRole: 'TEAM_LEAD', currentlyAccepted: false, checklist: [], evidence: [] }] });
    await page.addInitScript(() => { sessionStorage.setItem('brainserve.connect.access-token', 'sprint9-access'); sessionStorage.setItem('brainserve.connect.refresh-token', 'sprint9-refresh'); });
    await page.route('http://backend.invalid/api/v1/**', async route => {
        const url = new URL(route.request().url()), path = url.pathname.replace('/api/v1', ''), method = route.request().method();
        if (path.startsWith('/work-analytics') || path.endsWith('/handover')) state.requests.push(`${method} ${path}${url.search}`);
        if (path === '/work-analytics/context') return state.contextError ? route.fulfill({ status: 503, json: { detail: 'Planning context unavailable' } }) : route.fulfill({ json: { metricVersion: 'sprint9.v1', officeZone: 'Asia/Kolkata', officeDate: '2026-10-04', scope, departmentOptions: [{ id: departmentId, name: 'Engineering' }], canReadWorkload: role !== 'CEO', canHandover: role !== 'CEO' } });
        if (path === '/work-analytics/workload') return route.fulfill({ json: { metricVersion: 'sprint9.v1', generatedAt: now, officeZone: 'Asia/Kolkata', officeDate: '2026-10-04', scope, departmentId, departmentName: 'Engineering', totals: { activeTasks: 3, dueToday: 1, upcoming: 1, overdueDelivery: 1, pendingReview: 1, blocked: 1, estimatedMinutes: 60, estimatedTasks: 1, unestimatedTasks: 2, capacityMinutes: null }, members: [
            { employeeId, userId, name: 'Original Worker', role: 'EMPLOYEE', eligible: true, unavailableReasons: [], activeTasks: 2, dueToday: 1, upcoming: 1, overdueDelivery: 0, pendingReview: 1, blocked: 0, estimatedMinutes: 60, estimatedTasks: 1, unestimatedTasks: 1, capacityMinutes: null },
            { employeeId: targetId, userId: null, name: 'Unavailable Member', role: 'EMPLOYEE', eligible: false, unavailableReasons: ['APPROVED_LEAVE', 'ACCOUNT_DISABLED'], activeTasks: 1, dueToday: 0, upcoming: 0, overdueDelivery: 1, pendingReview: 0, blocked: 1, estimatedMinutes: null, estimatedTasks: 0, unestimatedTasks: 1, capacityMinutes: null },
        ] } });
        if (path === '/work-analytics/summary') { if (state.summaryError) return route.fulfill({ status: 503, json: { detail: 'Metric source unavailable' } }); const trend = [{ date: url.searchParams.get('to')!, denominator: 2, numerator: 1, value: 50 }]; const summary: WorkSummary = { metricVersion: 'sprint9.v1', generatedAt: now, officeZone: 'Asia/Kolkata', scope, from: url.searchParams.get('from')!, to: url.searchParams.get('to')!, departmentId: url.searchParams.get('departmentId') || (role === 'CEO' ? null : departmentId), cards, stages: [{ stage: 'DELIVERY_REVIEW', sampleCount: 2, medianSeconds: 7200, p95Seconds: 14400, unresolved: 1, oldestUnresolvedSeconds: 86400, coverageKnown: 2, coverageTotal: 3 }], trend, departmentTrends: [{ departmentId, departmentName: 'Engineering', denominator: 2, numerator: 1, value: 50, trend }] }; return route.fulfill({ json: summary }); }
        if (/^\/work-analytics\/WORK\d+\/records$/.test(path)) { if (state.recordsDenied) return route.fulfill({ status: 403, json: { detail: 'Current metric scope denied' } }); const number = Number(url.searchParams.get('page') ?? 0); return route.fulfill({ json: { metricVersion: 'sprint9.v1', generatedAt: now, number, size: 20, totalElements: state.emptyRecords ? 0 : 21, totalPages: state.emptyRecords ? 0 : 2, items: state.emptyRecords ? [] : [{ id: taskId, title: number ? 'Last authorized observation' : 'First authorized observation', departmentId, departmentName: 'Engineering', employeeId, assigneeName: 'Original Worker', status: 'COMPLETED', originalDueDate: '2026-10-04', dueDate: '2026-10-04', occurredAt: now, detail: 'Current valid acceptance observation in this exact original-due cohort.' }] } }); }
        if (path.endsWith('/export.csv')) return state.exportOversize ? route.fulfill({ status: 422, json: { detail: 'Export exceeds 5,000 observations; narrow the period.' } }) : route.fulfill({ contentType: 'text/csv', body: 'metricVersion,metricId,title\r\nsprint9.v1,WORK07,Retained office report\r\n' });
        if (path === `/work-tasks/${taskId}/handover`) {
            if (method === 'GET') return route.fulfill({ json: state.view });
            const body = route.request().postDataJSON(); state.writes.push(body); if (state.handoverDelay) await new Promise(resolve => setTimeout(resolve, 700));
            if (state.handoverConflict) { state.handoverConflict = false; state.view = { ...state.view, taskVersion: 7 }; return route.fulfill({ status: 409, json: { detail: 'Worksheet changed during handover', errorCode: 'WORK_HANDOVER_VERSION_CONFLICT' } }); }
            expect(body.expectedVersion).toBe(state.view.taskVersion); state.view = { ...state.view, taskVersion: state.view.taskVersion + 1, currentEmployeeId: body.targetEmployeeId, currentAssigneeName: 'New Worker', history: [{ id: 'handover-a', fromEmployeeId: employeeId, fromName: 'Original Worker', toEmployeeId: targetId, toName: 'New Worker', actorUserId: userId, actorName: 'Planning Owner', reason: body.reason, effectiveAt: now, occurredAt: now, assignmentRevision: 1, previousSubmissionVersion: 1 }] };
            state.task = { ...state.task, version: state.view.taskVersion, employeeId: targetId, assigneeName: 'New Worker', status: 'ASSIGNED', employeeUpdate: null, submissionVersion: 1, allowedActions: [], lane: 'DELIVERY' };
            if (state.handoverUnknown) { state.handoverUnknown = false; return route.fulfill({ status: 503, json: { detail: 'Handover response unavailable' } }); }
            return route.fulfill({ json: state.view });
        }
        if (path === `/workboard/${taskId}`) return route.fulfill({ json: { item: state.task, history: [], historyTruncated: false } });
        if (path === `/work-tasks/${taskId}/planning`) return route.fulfill({ json: currentPlanning() });
        if (path === `/work-tasks/${taskId}/activity`) return route.fulfill({ json: { events: [], comments: [], eventsTruncated: false, commentPage: 0, commentSize: 20, totalComments: 0 } });
        if (['/auth/me', '/profile/me'].includes(path)) return route.fulfill({ json: profile });
        if (path === '/auth/security') return route.fulfill({ json: { mfaRequired: true, mfaEnrolled: true, mfaVerified: true, stepUpRequired: false } });
        if (path === '/team-leads/me/workspace') return route.fulfill({ json: { assignment: { assignmentId: 'assignment-a', departmentId, teamLeadUserId: userId, teamLeadEmployeeId: leadId, fullName: profile.fullName, email: profile.email }, department, employees: springPage([{ id: employeeId, employeeNumber: 'EMP-9', departmentId, displayName: 'Original Worker', officialEmail: 'worker@example.invalid', designation: 'Engineer', status: 'ACTIVE' }, { id: leadId, employeeNumber: 'LEAD-9', departmentId, displayName: profile.fullName, officialEmail: profile.email, designation: 'Lead', status: 'ACTIVE' }]) } });
        if (path === '/employees') return route.fulfill({ json: springPage([]) });
        if (['/departments', '/departments/visible'].includes(path)) return route.fulfill({ json: [department] });
        if (['/appointments', '/admin/staff-accounts'].includes(path)) return route.fulfill({ json: springPage([]) });
        if (path === '/work-tasks') return route.fulfill({ json: [state.task] });
        if (path === '/dashboard/summary') return route.fulfill({ json: { awaitingApproval: 0, activeVisits: 0, totalEmployees: 2, activeEmployees: 2, scope, departmentId: role === 'CEO' ? null : departmentId } });
        if (path === '/dashboard/cards') return route.fulfill({ status: 503, json: { detail: 'Existing business cards unavailable in this fixture' } });
        if (path === '/work-tasks/workspace') return route.fulfill({ json: { departmentId, departmentName: 'Engineering', departmentCode: 'ENG', eligibleAssignees: [{ employeeId, displayName: 'Original Worker', designation: 'Engineer', role: 'EMPLOYEE' }] } });
        if (path === '/workboard/preferences') return route.fulfill({ json: { revision: 0, layout: 'LIST', density: 'COMPACT', savedFilters: [] } });
        if (path === '/workboard') return route.fulfill({ json: { policyVersion: 'workboard.v1', generatedAt: now, officeZone: 'Asia/Kolkata', officeDate: '2026-10-04', scope: 'DEPARTMENT', departmentId, number: 0, size: 20, totalElements: 1, totalPages: 1, counts: { scopes: { TODAY: 1, CARRY_FORWARD: 0, HISTORY: 0, ALL: 1 }, quickFilters: { ALL: 1, MY_ACTIONS: 1, DUE_TODAY: 1, OVERDUE_DELIVERY: 0, AWAITING_MY_REVIEW: 1, RETURNED_FOR_REWORK: 0, BLOCKED: 0 } }, laneCounts: { DELIVERY: 0, REVIEW: 1, REWORK: 0, CLOSED: 0 }, items: [state.task] } });
        if (path === '/realtime/stream') return route.fulfill({ status: 204 });
        if (path.includes('unread')) return route.fulfill({ json: { unreadCount: 0 } });
        return route.fulfill({ json: [] });
    });
    await page.goto('/');
    if (role !== 'CEO') { await expect(page.getByRole('navigation', { name: 'Role workspace' }).getByRole('button', { name: 'Work board', exact: true })).toBeAttached(); const menu = page.getByRole('button', { name: 'Open navigation' }); if (await menu.isVisible()) await menu.click(); await page.getByRole('navigation', { name: 'Role workspace' }).getByRole('button', { name: 'Work board', exact: true }).click(); }
    await expect(page.getByRole('button', { name: 'Workload & analytics', exact: true })).toBeVisible(); expect(state.requests).toEqual([]); return state;
}
async function openAnalytics(page: Page) { await page.getByRole('button', { name: 'Workload & analytics', exact: true }).click(); await expect(page.getByRole('region', { name: 'Work metrics', exact: true })).toBeVisible(); }
async function openHandover(page: Page) { await page.getByRole('button', { name: 'View details for Retained office report', exact: true }).click(); const drawer = page.getByRole('dialog', { name: 'Retained office report', exact: true }); await expect(drawer).toBeVisible(); await drawer.getByRole('tab', { name: 'Handover', exact: true }).click(); await expect(drawer.getByRole('region', { name: 'Worksheet handover' })).toContainText('Original Worker'); return drawer; }
async function handoverForm(page: Page) { const drawer = await openHandover(page); await drawer.getByRole('button', { name: 'Handover worksheet', exact: true }).click(); const dialog = page.getByRole('dialog', { name: 'Handover worksheet', exact: true }); await expect(dialog).toBeVisible(); await dialog.getByLabel('New department assignee', { exact: true }).selectOption(targetId); await dialog.getByLabel('Handover reason', { exact: true }).fill('Coverage for approved assignment transition.'); return dialog; }
for (const width of [360, 768, 1440]) test(`work planning at ${width}px keeps full cohort facts and keyboard handover usable`, async ({ page }, testInfo) => {
    await page.setViewportSize({ width, height: 900 }); const errors: string[] = []; page.on('pageerror', error => errors.push(error.message)); await fixture(page); await openAnalytics(page);
    const workspace = page.getByRole('region', { name: 'Workload and work analytics', exact: true }); await expect(workspace.getByRole('article')).toHaveCount(16); await expect(workspace).toContainText('Capacity is unknown'); await expect(workspace).toContainText('approved leave; account disabled'); await expect(workspace.getByRole('article', { name: 'WORK07 Original commitment acceptance' })).toContainText('1 / 2'); await expect(workspace).toContainText('Small sample');
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true); await page.screenshot({ path: testInfo.outputPath(`sprint9-work-planning-${width}.png`) });
    const dialog = await handoverForm(page); for (let i = 0; i < 8; i++) await page.keyboard.press('Tab'); expect(await page.evaluate(() => document.activeElement?.closest('dialog')?.getAttribute('aria-labelledby'))).toBe('handover-form-title'); await expect.poll(() => dialog.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true); await page.screenshot({ path: testInfo.outputPath(`sprint9-handover-${width}.png`) });
    await dialog.getByRole('button', { name: 'Confirm immediate handover', exact: true }).click(); await expect(dialog).toHaveCount(0); const drawer = page.getByRole('dialog', { name: 'Retained office report', exact: true }); await expect(drawer.getByRole('button', { name: 'Handover worksheet', exact: true })).toBeFocused(); await expect(drawer).toContainText('Handover confirmed to New Worker'); await expect(drawer.getByRole('region', { name: 'Retained handover history', exact: true })).toContainText('Original Worker → New Worker'); expect(errors).toEqual([]);
});
test('metric period, page and CSV export reconcile exact filters and definitions with current records', async ({ page }) => {
    const state = await fixture(page); await openAnalytics(page); await page.getByLabel('Metric start office date', { exact: true }).fill('2026-10-01'); await expect(page.getByRole('region', { name: 'Work metrics', exact: true })).toHaveCount(0); await page.getByLabel('Metric department', { exact: true }).selectOption(departmentId); await page.getByRole('button', { name: 'Apply metric period', exact: true }).click();
    const opener = page.getByRole('button', { name: 'View WORK07 records', exact: true }); await opener.click(); const dialog = page.getByRole('dialog', { name: 'Original commitment acceptance records', exact: true }); await expect(dialog).toContainText('First authorized observation'); await dialog.getByRole('button', { name: 'Next metric page', exact: true }).click(); await expect(dialog).toContainText('Last authorized observation');
    const download = page.waitForEvent('download'); await dialog.getByRole('button', { name: 'Export WORK07 CSV', exact: true }).click(); expect((await download).suggestedFilename()).toBe('WORK07-2026-10-01-2026-10-04-sprint9.v1.csv');
    for (const request of state.requests.filter(value => /WORK07\/(records|export)/.test(value))) { const query = new URLSearchParams(request.split('?')[1]); expect(query.get('from')).toBe('2026-10-01'); expect(query.get('to')).toBe('2026-10-04'); expect(query.get('departmentId')).toBe(departmentId); expect(query.get('metricVersion')).toBe('sprint9.v1'); }
    await page.keyboard.press('Escape'); await expect(dialog).toHaveCount(0); await expect(opener).toBeFocused();
});
test('handover conflicts retain fields and require current assignment reload and explicit review', async ({ page }) => {
    const state = await fixture(page); state.handoverConflict = true; const dialog = await handoverForm(page); await dialog.getByRole('button', { name: 'Confirm immediate handover', exact: true }).click(); await expect(dialog).toContainText('This worksheet changed'); await expect(dialog.getByLabel('Handover reason', { exact: true })).toHaveValue('Coverage for approved assignment transition.'); await expect(dialog.getByRole('button', { name: 'Confirm immediate handover', exact: true })).toBeDisabled();
    await dialog.getByRole('button', { name: 'Reload assignment and retain handover fields', exact: true }).click(); await expect(dialog).toContainText('version 7'); await expect(dialog.getByRole('button', { name: 'Confirm immediate handover', exact: true })).toBeDisabled(); expect(state.writes).toHaveLength(1); await dialog.getByRole('button', { name: 'I reviewed the current assignment and history', exact: true }).click(); await dialog.getByRole('button', { name: 'Confirm immediate handover', exact: true }).click(); await expect(dialog).toHaveCount(0); expect(state.writes[1].expectedVersion).toBe(7);
});
test('unconfirmed saved handover cannot replay or attribute retained evidence to the new assignee', async ({ page }) => {
    const state = await fixture(page); state.handoverUnknown = true; const dialog = await handoverForm(page); await dialog.getByRole('button', { name: 'Confirm immediate handover', exact: true }).click(); await expect(dialog).toContainText('response did not confirm'); await expect(dialog.getByLabel('Handover reason', { exact: true })).toBeDisabled(); await page.keyboard.press('Escape'); await expect(dialog).toBeVisible(); expect(state.writes).toHaveLength(1);
    await dialog.getByRole('button', { name: 'Reload assignment and retain handover fields', exact: true }).click(); await expect(dialog).toContainText('Current: New Worker'); await expect(dialog.getByRole('button', { name: 'Confirm immediate handover', exact: true })).toBeDisabled(); await dialog.getByRole('button', { name: 'Close handover form', exact: true }).click(); await page.getByRole('dialog', { name: 'Keep unsaved handover fields?', exact: true }).getByRole('button', { name: 'Discard handover form', exact: true }).click(); const drawer = page.getByRole('dialog', { name: 'Retained office report', exact: true }); await drawer.getByRole('button', { name: 'Reload worksheet', exact: true }).count();
    await drawer.getByRole('tab', { name: 'Planning & evidence', exact: true }).click(); await expect(drawer.getByText('Version 1 · by Original Worker · Historical acceptance retained', { exact: true })).toBeVisible(); await expect(drawer).not.toContainText('Version 1 · by New Worker'); expect(state.writes).toHaveLength(1);
});
test('session changes clear names, handover drafts, analytics and delayed mutation completions', async ({ page }) => {
    const state = await fixture(page); await openAnalytics(page); state.handoverDelay = true; const dialog = await handoverForm(page); await dialog.getByRole('button', { name: 'Confirm immediate handover', exact: true }).click(); await page.evaluate(() => window.dispatchEvent(new Event('brainserve:auth-session-changed'))); await expect(dialog).toHaveCount(0); const workspace = page.getByRole('region', { name: 'Workload and work analytics', exact: true }); await expect(workspace).not.toContainText('Original Worker'); await expect(workspace).not.toContainText('Unavailable Member'); await expect(page.getByRole('region', { name: 'Worksheet handover', exact: true })).toHaveCount(0); await page.waitForTimeout(800); await expect(page.getByRole('region', { name: 'Worksheet handover', exact: true })).toHaveCount(0);
});
test('empty observations, failed sources, bounded exports and record access loss are distinct and recoverable', async ({ page }) => {
    const state = await fixture(page); state.contextError = true; await page.getByRole('button', { name: 'Workload & analytics', exact: true }).click(); const workspace = page.getByRole('region', { name: 'Workload and work analytics', exact: true }); await expect(workspace).toContainText('Planning context unavailable'); state.contextError = false; await workspace.getByRole('button', { name: 'Retry work planning', exact: true }).click(); await expect(page.getByRole('region', { name: 'Work metrics', exact: true })).toBeVisible(); state.emptyRecords = true; await page.getByRole('button', { name: 'View WORK07 records', exact: true }).click(); const dialog = page.getByRole('dialog', { name: 'Original commitment acceptance records', exact: true }); await expect(dialog).toContainText('No authorized observations'); state.exportOversize = true; await dialog.getByRole('button', { name: 'Export WORK07 CSV', exact: true }).click(); await expect(dialog.getByRole('alert')).toContainText('5,000'); state.recordsDenied = true; await dialog.getByRole('button', { name: 'Reload metric records', exact: true }).click(); await expect(dialog).toHaveCount(0); await expect(workspace).not.toContainText('Original Worker'); await expect(workspace).toContainText('access changed');
});
test('CEO existing business dashboard opens company analytics without a workload enumeration', async ({ page }) => {
    const state = await fixture(page, 'CEO'); await openAnalytics(page); const workspace = page.getByRole('region', { name: 'Workload and work analytics', exact: true }); await expect(workspace).toContainText('company scope'); await expect(workspace.getByRole('region', { name: 'Current department workload', exact: true })).toHaveCount(0); expect(state.requests.some(value => value.includes('/workload'))).toBe(false); await workspace.locator('summary').filter({ hasText: 'Engineering original commitment trend' }).click(); await expect(workspace).toContainText('50%');
});
