CREATE INDEX IF NOT EXISTS idx_appointment_past_cancellation
    ON appointment (slot_end, status)
    WHERE status IN (
        'DRAFT', 'PENDING_VERIFICATION', 'PENDING_SECURITY_INTAKE',
        'PENDING_RECEPTION_VERIFICATION', 'PENDING_APPROVAL',
        'PENDING_HR_APPROVAL', 'PENDING_TEAM_LEAD_APPROVAL',
        'PENDING_CEO_APPROVAL', 'APPROVED', 'RESCHEDULE_REQUESTED', 'RESCHEDULED'
    );
