"use client";

import type { WorkTask } from "../types/workboard";
import { nextBusinessDays, officeToday } from "../../../lib/appointments";
import { PageTitle } from "../../../components/ui/page-title";
import { type Role } from "../../../types/workspace";
import { visitorInitials } from "../../appointments/appointment-utils";
import { WorkTaskPill } from "../components/work-task-pill";
import { workTaskStatusLabel } from "../utils/work-utils";
import { ArrowRight, BadgeCheck, BriefcaseBusiness, Building2, CalendarDays, Check, CheckCircle2, ChevronRight, CircleUserRound, Clock3, FileClock, FileText, MessageSquare, RotateCcw, Search, Send, ShieldCheck, X } from "lucide-react";
import { useWorkboard } from "../hooks/use-workboard";
import type { WorkboardProps } from "../types/props";

export function WorkBoard(props: WorkboardProps) {
    const { role, decideAppointment, onNavigate } = props;
    const { tasks, showCreate, setShowCreate, query, setQuery, statusFilter, setStatusFilter, branchFilter, setBranchFilter, queueScope, setQueueScope, expandedTaskId, setExpandedTaskId, busy, message, error, loadError, refreshWarning, loading, pendingHrAuditTaskIds, actionDialog, setActionDialog, actionNote, setActionNote, assignedDepartment, eligibleAssignees, createTask, act, auditHrTask, openTaskAction, submitTaskAction, isInsightsReworkCycle, isReworkCycle, reworkFeedback, reworkSourceName, reworkSourceLabel, taskActionCopy, isTodayTask, todayTasks, carryForwardTasks, queueTasks, branches, filtered, employeeName, pendingVisitorApprovals, insightReworkQueue, metric, pendingHrAuditCount, canProgress, canReviseRework, taskStageLabel } = useWorkboard(props);
    return <section className="work-board-page">
        <PageTitle eyebrow="DEPARTMENT TASK SHEETS" title={role === "HR Admin" ? "Department work board" : role === "Team Lead" ? "Team task sheets" : role === "Manager" ? "Department work oversight" : "My task sheets"}
                   detail={role === "HR Admin" ? "Assign work to active Employees or your department Team Lead, then audit completed delivery before Manager and CEO review."
                       : role === "Team Lead" ? "Assign work to Employees, review their delivery, and complete worksheets assigned to you by HR."
                           : role === "Manager" ? "Monitor task delivery in your assigned department. Verify HR-audited work in Work oversight before it reaches the CEO."
                               : "Only task sheets assigned to your Employee profile appear here. Other employees’ work is never shown."}
                   action={role === "Manager" ? <button className="button button-primary" onClick={() => onNavigate("insights")}><ShieldCheck size={17} /> Open work oversight</button>
                       : (["HR Admin", "Team Lead"] as Role[]).includes(role) && <button className="button button-primary" onClick={() => setShowCreate((value) => !value)}><FileText size={17} /> {showCreate ? "Close task form" : "Create task sheet"}</button>} />
        <div className="work-notification-note glass-panel"><MessageSquare size={19} /><span><strong>Visitor updates stay in Notifications</strong><small>Appointments no longer occupy Employee or Team Lead navigation. HR visitor cards and workflow decisions are delivered through the internal message service.</small></span></div>
        {role === "Team Lead" && insightReworkQueue.length > 0 && <section className="work-rework-alert glass-panel"><span><RotateCcw size={20} /></span><div><small>INSIGHTS ACTION REQUIRED</small><strong>{insightReworkQueue.length} worksheet{insightReworkQueue.length === 1 ? "" : "s"} returned for rework</strong><p>Review the HR, Manager or CEO feedback and create a corrective plan. The assignee cannot restart until you provide guidance.</p></div><button className="button button-primary" onClick={() => { setQueueScope(insightReworkQueue.some(isTodayTask) ? "TODAY" : "CARRY_FORWARD"); setStatusFilter("INSIGHT_REWORK_REQUESTED"); setBranchFilter("ALL"); window.scrollTo({ top: 560, behavior: "smooth" }); }}>Review returned work</button></section>}
        <section className="work-metrics glass-panel">
            <div><span>{queueScope === "TODAY" ? "Today’s sheets" : "Open carry-forward"}</span><strong>{queueTasks.length}</strong><small>{queueScope === "TODAY" ? "Created today" : "Older work still requiring action"}</small></div><i />
            <div><span>In progress</span><strong>{metric(["IN_PROGRESS", "CHANGES_REQUESTED"])}</strong><small>Currently being worked</small></div><i />
            <div><span>Awaiting review</span><strong>{role === "HR Admin" ? pendingHrAuditCount : metric(["COMPLETED"])}</strong><small>{role === "HR Admin" ? "HR audit action required" : role === "Manager" ? "Review progress before HR handoff" : "Team Lead action required"}</small></div><i />
            <div><span>Insights rework</span><strong>{metric(["INSIGHT_REWORK_REQUESTED"])}</strong><small>HR, Manager or CEO feedback</small></div>
        </section>
        {showCreate && <form className="work-create-form task-sheet-form panel glass-panel" onSubmit={createTask}>
            <div className="panel-heading"><div><span>NEW TASK SHEET</span><h2>Create a department worksheet</h2><p>{role === "HR Admin" ? "Select an active Employee or your department Team Lead. A Team Lead’s own delivery goes directly to HR audit and can never be self-approved." : "Select one active Employee in your department. Team Leads cannot assign a worksheet to themselves."}</p></div><FileText size={22} /></div>
            <div className="modal-form-grid"><label>Department assignee<select name="employeeId" required defaultValue=""><option value="" disabled>Select an eligible department member</option>{eligibleAssignees.map((item) => <option key={item.employeeId} value={item.employeeId}>{item.displayName} · {item.role === "TEAM_LEAD" ? "Team Lead" : item.designation || "Employee"}</option>)}</select></label>
                <label>Department / branch<input value={assignedDepartment ? `${assignedDepartment.name} · ${assignedDepartment.code}` : "No department assigned"} readOnly aria-readonly="true" /></label>
                <label>Task<input name="title" minLength={3} maxLength={160} required placeholder="What should the employee complete?" /></label>
                <label>Due date<input name="dueDate" type="date" min={officeToday()} defaultValue={nextBusinessDays(3)[0]} required /></label>
                <label className="full-field">Worksheet instructions<textarea name="description" minLength={5} maxLength={1000} required placeholder="Describe the work, expected result and acceptance criteria" /></label></div>
            <div className="modal-actions"><button type="button" className="button button-secondary" onClick={() => setShowCreate(false)}>Cancel</button><button className="button button-primary" disabled={busy === "create" || eligibleAssignees.length === 0 || !assignedDepartment}><Send size={16} />{busy === "create" ? "Creating…" : "Create sheet & notify"}</button></div>
            {!assignedDepartment && <div className="login-error" role="alert">Your account has no active department assignment. Complete the role-to-department assignment before creating work.</div>}
            {assignedDepartment && eligibleAssignees.length === 0 && <div className="login-error" role="alert">No eligible active Employee or Team Lead login is available in {assignedDepartment.name}.</div>}
        </form>}
        <section className="work-period-panel glass-panel" aria-label="Worksheet period">
            <div className="work-period-tabs" role="group" aria-label="Choose worksheet period">
                <button type="button" className={queueScope === "TODAY" ? "active" : ""} aria-pressed={queueScope === "TODAY"} onClick={() => { setQueueScope("TODAY"); setBranchFilter("ALL"); setStatusFilter("ALL"); setExpandedTaskId(null); }}><CalendarDays size={17} /><span><strong>Today</strong><small>Current worksheets</small></span><b>{todayTasks.length}</b></button>
                <button type="button" className={queueScope === "CARRY_FORWARD" ? "active" : ""} aria-pressed={queueScope === "CARRY_FORWARD"} onClick={() => { setQueueScope("CARRY_FORWARD"); setBranchFilter("ALL"); setStatusFilter("ALL"); setExpandedTaskId(null); }}><FileClock size={17} /><span><strong>Open carry-forward</strong><small>Older work requiring action</small></span><b>{carryForwardTasks.length}</b></button>
            </div>
            <div className="work-scope-summary"><Building2 size={17} aria-hidden="true" /><span><small>DEPARTMENT SCOPE</small><strong>{assignedDepartment ? `${assignedDepartment.name} · ${assignedDepartment.code}` : "Department assignment unavailable"}</strong></span></div>
            <p>Closed older worksheets stay stored for governance and audit, but no longer crowd the daily work board.</p>
        </section>
        <div className="work-toolbar glass-panel"><div><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={queueScope === "TODAY" ? "Search today’s worksheets" : "Search open carry-forward"} /></div><select aria-label="Department scope" value={branchFilter} onChange={(event) => setBranchFilter(event.target.value)} disabled={branches.length <= 1}><option value="ALL">{assignedDepartment ? assignedDepartment.name : "Assigned department"}</option>{branches.length > 1 && branches.map((item) => <option key={item}>{item}</option>)}</select><select aria-label="Worksheet status" value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)}><option value="ALL">All statuses</option>{(["ASSIGNED", "IN_PROGRESS", "COMPLETED", "CHANGES_REQUESTED", "INSIGHT_REWORK_REQUESTED", "APPROVED", "ACKNOWLEDGED"] as WorkTask["status"][]).map((item) => <option key={item} value={item}>{workTaskStatusLabel(item)}</option>)}</select></div>
        {(loadError || refreshWarning) && <div className={`work-refresh-state ${loadError ? "is-error" : "is-warning"}`} role={loadError ? "alert" : "status"}><RotateCcw size={17} aria-hidden="true" /><span><strong>{loadError ? "Work Board is reconnecting" : "Showing the last successful update"}</strong><small>{loadError || refreshWarning} The board refreshes automatically when the service recovers.</small></span></div>}
        <div className="task-sheet-grid">
            {loading && tasks.length === 0 && <div className="empty-state task-sheet-empty work-loading-state" role="status" aria-live="polite"><RotateCcw size={29} /><strong>Loading your department worksheets</strong><small>Existing records will stay visible during future background refreshes.</small></div>}
            {filtered.map((task) => {
                const expanded = expandedTaskId === task.id;
                const detailsId = `work-task-${task.id}-details`;
                const stageLabel = taskStageLabel(task);
                const feedback = reworkFeedback(task);
                return <article className={`task-sheet-card glass-panel${expanded ? " is-expanded" : ""}`} key={task.id}
                                aria-labelledby={`work-task-${task.id}-title`}>
                    <header><div><span className="task-sheet-label"><FileText size={14} /> TASK SHEET</span><small>#{task.id.slice(-8).toUpperCase()}</small></div><WorkTaskPill status={task.status} label={stageLabel} /></header>
                    <div className="task-sheet-summary">
                        <span className="work-category">{task.departmentBranch}</span>
                        <div className="task-sheet-summary-main">
                            <span className="task-sheet-summary-icon" aria-hidden="true"><BriefcaseBusiness size={17} /></span>
                            <div><span>WORK TO COMPLETE</span><h2 id={`work-task-${task.id}-title`}>{task.title}</h2><p>{task.description}</p></div>
                        </div>
                        <div className="task-sheet-summary-meta">
                            <span><CircleUserRound size={15} aria-hidden="true" /><small>Assigned to</small><strong>{role === "Employee" ? "You" : employeeName(task.employeeId)}</strong></span>
                            <span><CalendarDays size={15} aria-hidden="true" /><small>Due</small><strong>{new Date(`${task.dueDate}T00:00:00`).toLocaleDateString("en-IN", { day: "numeric", month: "short" })}</strong></span>
                        </div>
                        <div className="task-sheet-summary-alert-slot">{feedback && <span className="task-sheet-rework-flag"><RotateCcw size={14} /> Rework feedback{isInsightsReworkCycle(task) ? ` · cycle ${Math.max(1, task.reworkCycle ?? 0)}` : ""}</span>}</div>
                    </div>
                    <section className="task-sheet-details" id={detailsId} aria-label="Worksheet details" hidden={!expanded}>
                        <section className="task-sheet-brief" aria-label="Full work instructions"><span>FULL INSTRUCTIONS</span><p>{task.description}</p></section>
                        <div className="task-sheet-fields"><div><span>Assigned to</span><strong>{role === "Employee" ? "Assigned to you" : employeeName(task.employeeId)} · {task.assigneeRole === "TEAM_LEAD" ? "Team Lead" : "Employee"}</strong></div><div><span>Assigned by</span><strong>{task.assignedByRole === "HR_ADMIN" ? "HR Admin" : "Team Lead"}</strong></div><div><span>Due date</span><strong>{new Date(`${task.dueDate}T00:00:00`).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" })}</strong></div><div><span>Current stage</span><strong>{stageLabel}</strong></div></div>
                        <div className="task-flow" aria-label={`Worksheet stage: ${workTaskStatusLabel(task.status)}`}><span className="done"><i>1</i>Assigned</span><b /><span className={["IN_PROGRESS", "COMPLETED", "APPROVED", "ACKNOWLEDGED", "CHANGES_REQUESTED"].includes(task.status) ? "done" : task.status === "ASSIGNED" ? "current" : ""}><i>2</i>{task.assigneeRole === "TEAM_LEAD" ? "Team Lead work" : "Employee work"}</span><b />{task.assigneeRole === "EMPLOYEE" && <><span className={["APPROVED", "ACKNOWLEDGED"].includes(task.status) ? "done" : task.status === "COMPLETED" ? "current" : ""}><i>3</i>Team Lead review</span><b /></>}<span className={task.status === "INSIGHT_REWORK_REQUESTED" ? "returned" : (task.assigneeRole === "TEAM_LEAD" && task.status === "COMPLETED") || ["APPROVED", "ACKNOWLEDGED"].includes(task.status) ? "current" : ""}><i>{task.assigneeRole === "TEAM_LEAD" ? 3 : 4}</i>HR → Manager → CEO</span></div>
                        {feedback && <div className="insight-rework-card"><span><RotateCcw size={15} /> {isInsightsReworkCycle(task) ? `INSIGHTS REWORK · CYCLE ${Math.max(1, task.reworkCycle ?? 0)}` : "TEAM LEAD REWORK"}</span><strong>{reworkSourceName(task)} feedback</strong><p>{feedback}</p>{task.status === "INSIGHT_REWORK_REQUESTED" && <small>Waiting for the Team Lead to record a corrective plan.</small>}</div>}
                        {(task.employeeUpdate || task.teamLeadReview) && <div className="task-sheet-responses">{task.employeeUpdate && <div><span>{task.assigneeRole === "TEAM_LEAD" ? "Team Lead work update" : "Employee work update"}</span><p>{task.employeeUpdate}</p></div>}{task.teamLeadReview && <div><span>Team Lead decision</span><p>{task.teamLeadReview}</p></div>}</div>}
                    </section>
                    <footer className="work-task-actions">
                        {expanded && <>
                            {canProgress(task) && ["ASSIGNED", "CHANGES_REQUESTED"].includes(task.status) && <button className="button button-secondary" disabled={Boolean(busy)} onClick={() => openTaskAction(task, "start")}><Clock3 size={14} /> {isReworkCycle(task) ? "Start rework" : "Start"}</button>}
                            {canProgress(task) && ["ASSIGNED", "IN_PROGRESS", "CHANGES_REQUESTED"].includes(task.status) && <button className="button button-primary" disabled={Boolean(busy)} onClick={() => openTaskAction(task, "complete")}><CheckCircle2 size={14} /> {isReworkCycle(task) ? "Submit corrected work" : "Complete"}</button>}
                            {role === "Team Lead" && task.assigneeRole === "EMPLOYEE" && task.status === "COMPLETED" && <><button className="button button-reject" disabled={Boolean(busy)} onClick={() => openTaskAction(task, "request-changes")}><X size={14} /> Request changes</button><button className="button button-approve" disabled={Boolean(busy)} onClick={() => openTaskAction(task, "approve")}><BadgeCheck size={14} /> Approve delivery</button></>}
                            {role === "Team Lead" && task.status === "INSIGHT_REWORK_REQUESTED" && <button className="button button-primary" disabled={Boolean(busy)} onClick={() => openTaskAction(task, "insight-rework")}><RotateCcw size={14} /> {task.assigneeRole === "TEAM_LEAD" ? "Start rework" : "Create rework plan"}</button>}
                            {canReviseRework(task) && <button className="button button-primary" disabled={Boolean(busy)} onClick={() => openTaskAction(task, "revise-rework")}><RotateCcw size={14} /> Update & resubmit</button>}
                            {role === "Employee" && task.status === "APPROVED" && <button className="button button-approve" disabled={Boolean(busy)} onClick={() => void act(task, "acknowledge")}><BadgeCheck size={14} /> Acknowledge</button>}
                            {role === "HR Admin" && pendingHrAuditTaskIds.has(task.id) && <><button className="button button-reject" disabled={Boolean(busy)} onClick={() => openTaskAction(task, "hr-rework")}><RotateCcw size={14} /> Return for rework</button><button className="button button-approve" disabled={Boolean(busy)} onClick={() => void auditHrTask(task)}><ShieldCheck size={14} /> Audit & send to Manager</button></>}
                        </>}
                        <button type="button" className="button task-sheet-details-toggle" aria-expanded={expanded} aria-controls={detailsId} onClick={() => setExpandedTaskId(expanded ? null : task.id)}>{expanded ? "Hide details" : "View details"}<ChevronRight size={15} aria-hidden="true" /></button>
                    </footer>
                </article>;
            })}{!loading && filtered.length === 0 && <div className="empty-state task-sheet-empty"><FileText size={29} /><strong>{loadError ? "Worksheet data is temporarily unavailable" : queueScope === "TODAY" ? "No worksheets on today’s board" : "No open carry-forward work"}</strong><small>{loadError ? "The last confirmed data will return automatically after the database connection recovers." : queueScope === "TODAY" ? "New worksheets created today will appear here. Use Open carry-forward for unfinished work from earlier days." : "All older worksheets are closed or no longer require action. Their stored records remain available for governance and audit."}</small></div>}
        </div>
        {role === "Team Lead" && <article className="panel glass-panel work-visitor-approvals"><div className="panel-heading"><div><span>VISITOR WORKFLOW</span><h2>Department visitor approvals</h2><p>Visitor approval remains available here so removing Appointments never breaks Security → Reception → HR routing.</p></div><b>{pendingVisitorApprovals.length}</b></div>{pendingVisitorApprovals.map((item) => <div className="approval-item" key={item.id}><div className="approval-person"><span className="avatar">{item.initials}</span><span><strong>{item.visitor}</strong><small>Visiting {item.host} · {item.referenceNumber}</small></span></div><p>“{item.arrivalPurpose ?? item.purpose}”</p><div className="approval-actions"><button className="button button-reject" onClick={() => void decideAppointment(item.id, "reject")}><X size={15} /> Reject visit</button><button className="button button-approve" onClick={() => void decideAppointment(item.id, "approve")}><Check size={15} /> Approve visit</button></div></div>)}{pendingVisitorApprovals.length === 0 && <div className="empty-state"><ShieldCheck size={27} /><strong>No visitor approvals waiting</strong><small>HR-routed department visitors will appear here.</small></div>}</article>}
        {actionDialog && taskActionCopy && <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setActionDialog(null); }}><section className="modal work-action-modal" role="dialog" aria-modal="true" aria-labelledby="work-action-title"><header><div><span>WORKSHEET ACTION</span><h2 id="work-action-title">{taskActionCopy[0]}</h2><p>{taskActionCopy[1]}</p></div><button className="icon-button" type="button" onClick={() => setActionDialog(null)} aria-label="Close worksheet action"><X size={18} /></button></header><form onSubmit={submitTaskAction}><div className="work-action-context"><span className="avatar">{visitorInitials(employeeName(actionDialog.task.employeeId))}</span><span><small>{actionDialog.task.departmentBranch} · {taskStageLabel(actionDialog.task)}</small><strong>{actionDialog.task.title}</strong></span></div>{["insight-rework", "revise-rework"].includes(actionDialog.action) && reworkFeedback(actionDialog.task) && <div className="modal-review-source"><RotateCcw size={16} /><span><small>{reworkSourceLabel(actionDialog.task)}</small><strong>{reworkFeedback(actionDialog.task)}</strong></span></div>}<label>{taskActionCopy[2]}<textarea value={actionNote} onChange={(event) => setActionNote(event.target.value)} placeholder={taskActionCopy[3]} minLength={["complete", "request-changes", "insight-rework", "revise-rework", "hr-rework"].includes(actionDialog.action) ? 5 : undefined} maxLength={1000} required={["complete", "request-changes", "insight-rework", "revise-rework", "hr-rework"].includes(actionDialog.action)} autoFocus /></label><small className="dialog-character-count">{actionNote.length}/1000</small>{error && <div className="login-error" role="alert">{error}</div>}<div className="modal-actions"><button type="button" className="button button-secondary" onClick={() => setActionDialog(null)}>Cancel</button><button className="button button-primary" disabled={Boolean(busy)}>{busy ? "Saving…" : taskActionCopy[4]}<ArrowRight size={15} /></button></div></form></section></div>}
        {message && <div className="success-banner"><CheckCircle2 size={17} />{message}</div>}{error && !actionDialog && <div className="login-error" role="alert">{error}</div>}
    </section>;
}
