"use client";
import { DraftStatus } from "../../drafts/draft-status";
import { draftBlocksSubmit, draftLocksFields } from "../../drafts/use-form-draft";
import draftStyles from "../../drafts/drafts.module.css";
import { useEffect, useRef, useState } from "react";
import type { WorkTask, WorkboardAction, WorkboardItem, WorkboardLane, WorkboardScope, WorkboardQuickFilter } from "../types/workboard";
import { nextBusinessDays, officeToday } from "../../../lib/appointments";
import { PageTitle } from "../../../components/ui/page-title";
import { FileText, MessageSquare, Search, Send, ShieldCheck, X, Check, CheckCircle2, RotateCcw, ArrowRight, List, Columns3 } from "lucide-react";
import { WorkTaskPill } from "../components/work-task-pill";
import { WorkDialog } from "../components/work-dialog";
import { WorkTaskDrawer, actionLabels } from "../components/work-task-drawer";
import { useWorkboard } from "../hooks/use-workboard";
import { workTaskStatusLabel } from "../utils/work-utils";
import { periodLabels, quickFilterLabels, workActorName } from "../utils/workboard-model";
import type { WorkboardProps } from "../types/props";

export function WorkBoard(props: WorkboardProps) {
    const { role, decideAppointment, onNavigate, initialTaskId } = props;
    const board = useWorkboard(props);
    const { showCreate, setShowCreate, query, setQuery, statusFilter, setStatusFilter, branchFilter, setBranchFilter, queueScope, setQueueScope,
        quickFilter, setQuickFilter, sort, setSort, page, setPage, size, setSize, criteria, applyCriteria, resetCriteria, boardPage, preferences,
        savePreferences, preferenceBusy, preferenceError, reloadPreferences, expandedTaskId, setExpandedTaskId, selectedDetail, detailError, reloadDetail,
        busy, message, error, loadError, refreshWarning, loading, actionDialog, setActionDialog, actionNote, setActionNote, assignedDepartment,
        eligibleAssignees, createTask, act, auditHrTask, openTaskAction, submitTaskAction, taskActionCopy, pendingVisitorApprovals, taskStageLabel, conflict, reloadConflict, actionDirty } = board;
    const openedFromSearch = useRef<string | null>(null);
    useEffect(() => {
        if (initialTaskId && !loading && boardPage && openedFromSearch.current !== initialTaskId) {
            openedFromSearch.current = initialTaskId; setExpandedTaskId(initialTaskId);
        }
    }, [initialTaskId, loading, boardPage, setExpandedTaskId]);
    const [filterName, setFilterName] = useState(""), [createDirty, setCreateDirty] = useState(false);
    useEffect(() => { if (!actionDirty && !(showCreate && createDirty)) return; const leaving = (event: BeforeUnloadEvent) => { event.preventDefault(); event.returnValue = ""; }; window.addEventListener("beforeunload", leaving); return () => window.removeEventListener("beforeunload", leaving); }, [actionDirty, showCreate, createDirty]);
    const closeAction = () => { if (!busy && (!actionDirty || window.confirm("Discard your unsaved worksheet note?"))) setActionDialog(null); };
    const closeCreate = () => { if (!busy && (!createDirty || window.confirm("Discard this unsaved task sheet?"))) { setShowCreate(false); setCreateDirty(false); } };
    const onAction = (task: WorkboardItem, action: WorkboardAction) => { if (action === "acknowledge") void act(task, action); else if (action === "hr-audit") void auditHrTask(task); else if (action === "open-oversight") onNavigate("insights"); else openTaskAction(task, action); };
    const items = boardPage?.items ?? [], counts = boardPage?.counts;
    const lanes: WorkboardLane[] = ["DELIVERY", "REVIEW", "REWORK", "CLOSED"];
    const laneLabels: Record<WorkboardLane, string> = { DELIVERY: "Delivery", REVIEW: "Review", REWORK: "Rework", CLOSED: "Closed" };
    const row = (task: WorkboardItem) => {
        const quick = (["start", "complete", "approve", "acknowledge", "insight-rework", "revise-rework", "hr-audit", "open-oversight"] as WorkboardAction[]).find((action) => task.allowedActions.includes(action));
        return <article key={task.id} className="workboard-row" aria-labelledby={`work-task-${task.id}-title`}>
        <div className="workboard-task"><small>{task.departmentBranch} · #{task.id.slice(-8).toUpperCase()}</small><h2 id={`work-task-${task.id}-title`}>{task.title}</h2><small>{task.priority ?? "NORMAL"}{task.blocked ? " · Blocked" : ""}</small><span>{task.nextActor ? `Next: ${workActorName(task.nextActor)}` : "Review complete"}</span></div>
        <div className="workboard-assignee"><small>Assigned to</small><strong>{role === "Employee" ? "You" : task.assigneeName}</strong></div><div className="workboard-due"><small>Due date</small><time dateTime={task.dueDate}>{task.dueDate}</time></div>
        <WorkTaskPill status={task.status} label={taskStageLabel(task)} /><div className="workboard-row-actions">{quick && <button type="button" className="button button-secondary" disabled={Boolean(busy)} aria-label={`${actionLabels[quick]} ${task.title}`} onClick={() => { if (quick !== "open-oversight") setExpandedTaskId(task.id); onAction(task, quick); }}>{actionLabels[quick]}</button>}
            <button type="button" className="button button-secondary" aria-haspopup="dialog" onClick={() => setExpandedTaskId(task.id)}>View details<span className="sr-only"> for {task.title}</span><ArrowRight size={16} /></button></div>
    </article>; };
    return <section className={`work-board-page workboard-v5 density-${preferences.density.toLowerCase()}`}>
        <PageTitle eyebrow="DEPARTMENT TASK SHEETS" title={role === "HR Admin" ? "Department work board" : role === "Team Lead" ? "Team task sheets" : role === "Manager" ? "Department work oversight" : "My task sheets"}
            detail={role === "HR Admin" ? "Assign department work and audit submitted delivery before Manager and CEO review." : role === "Team Lead" ? "Assign employee work, review delivery and complete the worksheets HR assigns to you." : role === "Manager" ? "Follow department delivery and review HR-audited work in Work oversight." : "Your own worksheets, current delivery and reviewer feedback in one place."}
            action={role === "Manager" ? <button className="button button-primary" onClick={() => onNavigate("insights")}><ShieldCheck size={17} />Open work oversight</button> : ["HR Admin", "Team Lead"].includes(role) && <button className="button button-primary" disabled={!board.canCreateTask} onClick={() => { setCreateDirty(false); setShowCreate(true); }}><FileText size={17} />Create task sheet</button>} />
        <div className="work-notification-note glass-panel"><MessageSquare size={19} /><span><strong>Visitor updates stay in Notifications</strong><small>Task delivery and visitor routing continue through the internal message service.</small></span></div>
        <section className="workboard-filters glass-panel" aria-label="Worksheet filters">
            <div className="workboard-period-header"><div className="workboard-periods" role="group" aria-label="Choose worksheet period">{(Object.keys(periodLabels) as WorkboardScope[]).map((scope) => <button key={scope} type="button" aria-pressed={queueScope === scope} className={queueScope === scope ? "active" : ""} onClick={() => setQueueScope(scope)}>{periodLabels[scope]}<b>{counts?.scopes[scope] ?? "—"}</b></button>)}</div>
            <div className="work-scope-summary"><span><small>{boardPage?.scope === "OWN" ? "YOUR WORKSHEETS" : "DEPARTMENT SCOPE"}</small><strong>{assignedDepartment ? `${assignedDepartment.name} · ${assignedDepartment.code}` : "Current authorized scope"}</strong></span></div></div>
            <div className="workboard-controls"><label className="workboard-search"><span>Search worksheets</span><div><Search size={18} aria-hidden="true" /><input type="search" value={query} maxLength={120} onChange={(event) => setQuery(event.target.value)} placeholder="Title, instructions or assignee" /></div></label>
                <label>Worksheet status<select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)}><option value="ALL">All statuses</option>{(["ASSIGNED", "IN_PROGRESS", "COMPLETED", "CHANGES_REQUESTED", "INSIGHT_REWORK_REQUESTED", "APPROVED", "ACKNOWLEDGED"] as WorkTask["status"][]).map((status) => <option key={status} value={status}>{workTaskStatusLabel(status)}</option>)}</select></label>
                <label>Department / branch filter<input value={branchFilter === "ALL" ? "" : branchFilter} maxLength={170} onChange={(event) => setBranchFilter(event.target.value || "ALL")} placeholder="Exact branch name" /></label>
                <label>Sort worksheets<select value={sort} onChange={(event) => setSort(event.target.value as typeof sort)}><option value="DUE_DATE">Due date</option><option value="UPDATED_AT">Recently updated</option><option value="TITLE">Title</option><option value="PRIORITY">Priority</option></select></label></div>
            <div className="workboard-quick-filters" role="group" aria-label="Quick filters">{(Object.keys(quickFilterLabels) as WorkboardQuickFilter[]).map((quick) => <button key={quick} type="button" aria-pressed={quickFilter === quick} className={quickFilter === quick ? "active" : ""} onClick={() => setQuickFilter(quick)}>{quickFilterLabels[quick]}<b>{counts?.quickFilters[quick] ?? "—"}</b></button>)}</div>
            <div className="workboard-view-controls"><div role="group" aria-label="Worksheet layout"><button type="button" className="button button-secondary" aria-pressed={preferences.layout === "LIST"} disabled={preferenceBusy} onClick={() => void savePreferences({ layout: "LIST" })}><List size={17} />List</button><button type="button" className="button button-secondary" aria-pressed={preferences.layout === "BOARD"} disabled={preferenceBusy} onClick={() => void savePreferences({ layout: "BOARD" })}><Columns3 size={17} />Board</button></div>
                <label>Density<select value={preferences.density} disabled={preferenceBusy} onChange={(event) => void savePreferences({ density: event.target.value as typeof preferences.density })}><option value="COMPACT">Compact</option><option value="COMFORTABLE">Comfortable</option></select></label><button className="button button-secondary" type="button" onClick={resetCriteria}>Clear filters</button></div>
            <div className="workboard-options-row"><details className="workboard-saved-options"><summary>Saved filters{preferences.savedFilters.length ? ` (${preferences.savedFilters.length})` : ""}</summary><form className="workboard-saved-filters" onSubmit={(event) => { event.preventDefault(); if (!filterName.trim() || preferences.savedFilters.length >= 10) return; void savePreferences({ savedFilters: [...preferences.savedFilters, { ...criteria, id: crypto.randomUUID(), name: filterName.trim() }] }); }}>
                <label>Saved filters<select defaultValue="" onChange={(event) => { const selected = preferences.savedFilters.find((filter) => filter.id === event.target.value); if (selected) applyCriteria(selected); event.target.value = ""; }}><option value="">Choose a saved filter</option>{preferences.savedFilters.map((filter) => <option key={filter.id} value={filter.id}>{filter.name}</option>)}</select></label>
                <label>Filter name<input value={filterName} maxLength={60} onChange={(event) => setFilterName(event.target.value)} placeholder="Name these criteria" /></label><button className="button button-secondary" disabled={preferenceBusy || !filterName.trim() || preferences.savedFilters.length >= 10}>Save current filters</button></form>
            {preferences.savedFilters.length > 0 && <ul className="workboard-saved-list">{preferences.savedFilters.map((filter) => <li key={filter.id}><button type="button" onClick={() => applyCriteria(filter)}>{filter.name}</button><button type="button" aria-label={`Delete saved filter ${filter.name}`} disabled={preferenceBusy} onClick={() => void savePreferences({ savedFilters: preferences.savedFilters.filter((value) => value.id !== filter.id) })}><X size={16} /></button></li>)}</ul>}</details>
            <details className="workboard-help"><summary>How periods and action filters work</summary><p className="workboard-filter-help">Today means created on the current office date{boardPage ? ` (${boardPage.officeDate}, ${boardPage.officeZone})` : ""}. Open carry-forward keeps older work requiring action. History contains older closed work. My actions uses your current eligibility. Awaiting my review includes delivery decisions, corrective plans and audit reviews. Counts follow search, status, branch and period; quick counts allow comparison across action filters.</p></details></div>
            {preferenceError && <div role="alert" className="login-error">{preferenceError}<button className="button button-secondary" type="button" onClick={() => void reloadPreferences()}>Reload preferences</button></div>}
        </section>
        {(loadError || refreshWarning) && <div className={`work-refresh-state ${loadError ? "is-error" : "is-warning"}`} role={loadError ? "alert" : "status"}><RotateCcw size={17} /><span><strong>{loadError ? "Work Board is reconnecting" : "Showing the last successful update"}</strong><small>{loadError || refreshWarning}</small></span></div>}
        <section className="workboard-results glass-panel" aria-label="Worksheet results" aria-busy={loading}>
            <div className="workboard-result-heading"><h2 tabIndex={-1} data-workboard-focus>{boardPage ? `${boardPage.totalElements} matching worksheets` : "Worksheet counts unavailable"}</h2><span role="status">{loading ? "Refreshing worksheets…" : `${periodLabels[queueScope]} · ${quickFilterLabels[quickFilter]}`}</span></div><p className="workboard-filter-help">List and board show the same page. Stage totals include all matching worksheets, including other pages.</p>
            {preferences.layout === "LIST" ? <div className="workboard-list" aria-label="Worksheet list">{items.map(row)}</div> : <div className="workboard-lanes" aria-label="Paginated stage board">{lanes.map((lane) => <section key={lane} className="workboard-lane" aria-label={`${laneLabels[lane]} stage`}><h3>{laneLabels[lane]}<b>{boardPage?.laneCounts[lane] ?? "—"}</b></h3><p>{boardPage ? `${items.filter((item) => item.lane === lane).length} on this page` : "Stage count unavailable"}</p>{items.filter((item) => item.lane === lane).map(row)}</section>)}</div>}
            {!loading && items.length === 0 && <div className="empty-state"><FileText size={28} /><strong>{loadError ? "Worksheet data is temporarily unavailable" : "No worksheets match these filters"}</strong><small>Choose another period or clear filters to inspect your authorized work.</small></div>}
            <nav className="workboard-pagination" aria-label="Worksheet pagination"><label>Rows per page<select value={size} onChange={(event) => setSize(Number(event.target.value))}>{[10, 20, 50, 100].map((value) => <option key={value} value={value}>{value}</option>)}</select></label><span>{boardPage ? boardPage.totalElements ? `${page * size + 1}–${Math.min((page + 1) * size, boardPage.totalElements)} of ${boardPage.totalElements}` : "0 results" : "Count unavailable"} · Page {page + 1} of {Math.max(1, boardPage?.totalPages ?? 0)}</span>
                <button type="button" className="button button-secondary" disabled={loading || page === 0} onClick={() => setPage((value) => value - 1)}>Previous page</button><button type="button" className="button button-secondary" disabled={loading || page + 1 >= (boardPage?.totalPages ?? 0)} onClick={() => setPage((value) => value + 1)}>Next page</button></nav>
        </section>
        {role === "Team Lead" && <article className="panel glass-panel work-visitor-approvals"><div className="panel-heading"><div><span>VISITOR WORKFLOW</span><h2>Department visitor approvals</h2><p>Approve the department visitors routed by HR.</p></div><b>{pendingVisitorApprovals.length}</b></div>{pendingVisitorApprovals.map((item) => <div className="approval-item" key={item.id}><div className="approval-person"><span className="avatar">{item.initials}</span><span><strong>{item.visitor}</strong><small>Visiting {item.host} · {item.referenceNumber}</small></span></div><p>{item.arrivalPurpose ?? item.purpose}</p><div className="approval-actions"><button className="button button-reject" onClick={() => void decideAppointment(item.id, "reject")}><X size={15} />Reject visit</button><button className="button button-approve" onClick={() => void decideAppointment(item.id, "approve")}><Check size={15} />Approve visit</button></div></div>)}{pendingVisitorApprovals.length === 0 && <div className="empty-state"><ShieldCheck size={27} /><strong>No visitor approvals waiting</strong><small>HR-routed department visitors will appear here.</small></div>}</article>}
        {expandedTaskId && <WorkTaskDrawer key={expandedTaskId} id={expandedTaskId} detail={selectedDetail} error={detailError} busy={Boolean(busy)} onClose={() => setExpandedTaskId(null)} onReload={() => void reloadDetail()} onAction={onAction} stageLabel={taskStageLabel} />}
        {showCreate && <WorkDialog className="work-create-dialog" titleId="work-create-title" onClose={closeCreate}><form className="work-create-form" onChange={() => setCreateDirty(true)} onSubmit={async (event) => { if (await createTask(event)) setCreateDirty(false); }}>
            <header><div><small>NEW TASK SHEET</small><h2 id="work-create-title">Create a department worksheet</h2><p>{role === "HR Admin" ? "Assign an active Employee or your department Team Lead. Team Lead delivery goes directly to HR audit." : "Assign an active Employee in your department. Team Leads cannot assign themselves."}</p></div><button className="icon-button" type="button" aria-label="Close task form" onClick={closeCreate}><X size={20} /></button></header>
            <DraftStatus draft={board.createDraft} onRestore={(fields) => { board.setCreateFields(fields); setCreateDirty(true); }} onConfirmed={() => void board.confirmCreatedDraft()} />
            <fieldset disabled={board.createDraft.enabled && draftLocksFields(board.createDraft.state.phase)} className={`modal-form-grid ${draftStyles.fields}`}><label>Department assignee<select name="employeeId" required value={board.createFields.employeeId ?? ""} onChange={(event) => board.setCreateFields((fields) => ({ ...fields, employeeId: event.target.value }))}><option value="" disabled>Select an eligible department member</option>{eligibleAssignees.map((item) => <option key={item.employeeId} value={item.employeeId}>{item.displayName} · {item.role === "TEAM_LEAD" ? "Team Lead" : item.designation || "Employee"}</option>)}</select></label><label>Department / branch<input value={assignedDepartment ? `${assignedDepartment.name} · ${assignedDepartment.code}` : "No department assigned"} readOnly /></label>
                <label>Task<input name="title" value={board.createFields.title ?? ""} onChange={(event) => board.setCreateFields((fields) => ({ ...fields, title: event.target.value }))} minLength={3} maxLength={160} required placeholder="What should the employee complete?" /></label><label>Due date<input name="dueDate" type="date" min={officeToday()} value={board.createFields.dueDate ?? nextBusinessDays(3)[0]} onChange={(event) => board.setCreateFields((fields) => ({ ...fields, dueDate: event.target.value }))} required /></label><label className="full-field">Worksheet instructions<textarea name="description" value={board.createFields.description ?? ""} onChange={(event) => board.setCreateFields((fields) => ({ ...fields, description: event.target.value }))} minLength={5} maxLength={1000} required placeholder="Describe work, expected result and acceptance criteria" /></label></fieldset>
            {!assignedDepartment && <p className="login-error" role="alert">Your account has no active department assignment.</p>}{assignedDepartment && eligibleAssignees.length === 0 && <p className="login-error" role="alert">No eligible active department login is available.</p>}{error && <p className="login-error" role="alert">{error}</p>}<div className="modal-actions"><button className="button button-secondary" type="button" onClick={closeCreate}>Cancel</button><button className="button button-primary" disabled={Boolean(busy) || eligibleAssignees.length === 0 || !assignedDepartment || board.createDraft.enabled && draftBlocksSubmit(board.createDraft.state.phase)}><Send size={16} />{busy ? "Creating…" : "Create sheet & notify"}</button></div>
        </form></WorkDialog>}
        {actionDialog && taskActionCopy && <WorkDialog className="modal work-action-modal workboard-action-dialog" titleId="work-action-title" onClose={closeAction}><header><div><small>WORKSHEET ACTION</small><h2 id="work-action-title">{taskActionCopy[0]}</h2><p>{taskActionCopy[1]}</p></div><button className="icon-button" type="button" onClick={closeAction} aria-label="Close worksheet action"><X size={18} /></button></header>
            <form onSubmit={submitTaskAction}><DraftStatus draft={board.actionDraft} onRestore={(fields) => setActionNote(fields.note ?? "")} onConfirmed={() => void board.confirmActionDraft()} />{board.actionDraft.state.phase === "conflict" && <button className="button button-secondary" type="button" onClick={async () => { await reloadConflict(); await board.actionDraft.session.load(); }}>Reload current worksheet and retain note</button>}<div className="work-action-context"><strong>{actionDialog.task.title}</strong><small>Observed worksheet version {actionDialog.task.version}</small></div><label>{taskActionCopy[2]}<textarea data-initial-focus disabled={board.actionDraft.enabled && draftLocksFields(board.actionDraft.state.phase)} value={actionNote} onChange={(event) => setActionNote(event.target.value)} placeholder={taskActionCopy[3]} minLength={["complete", "request-changes", "insight-rework", "revise-rework", "hr-rework"].includes(actionDialog.action) ? 5 : undefined} maxLength={1000} required={["complete", "request-changes", "insight-rework", "revise-rework", "hr-rework"].includes(actionDialog.action)} autoFocus /></label><small className="dialog-character-count">{actionNote.length}/1000</small>
                {["complete", "insight-rework", "revise-rework"].includes(actionDialog.action) && (actionDialog.task.insightReviewReason || actionDialog.task.teamLeadReview) && <section className="modal-review-source"><div><small>Current reviewer feedback</small><p>{actionDialog.task.insightReviewReason ?? actionDialog.task.teamLeadReview}</p></div></section>}
                {error && <div className="login-error" role="alert">{error}{conflict && <><p>Your note is kept. Reload the worksheet and review its current stage before retrying.</p><button className="button button-secondary" type="button" onClick={() => void reloadConflict()}>Reload current worksheet</button></>}</div>}<div className="modal-actions"><button type="button" className="button button-secondary" onClick={closeAction}>Cancel</button><button className="button button-primary" disabled={Boolean(busy) || conflict || board.actionDraft.enabled && draftBlocksSubmit(board.actionDraft.state.phase) || ("allowedActions" in actionDialog.task && !(actionDialog.task as WorkboardItem).allowedActions.includes(actionDialog.action))}>{busy ? "Saving…" : taskActionCopy[4]}<ArrowRight size={15} /></button></div>
            </form></WorkDialog>}
        {message && <div className="success-banner" role="status"><CheckCircle2 size={17} />{message}</div>}{error && !actionDialog && !showCreate && <div className="login-error" role="alert">{error}</div>}
    </section>;
}
