import type { WorkMetric, WorkSummary, WorkTrend } from '../types';
import { durationLabel, metricValue } from '../planning-model';
import styles from '../planning.module.css';
function TrendRows({ items }: { items: WorkTrend[] }) {
    return items.length ? <table className={styles.table}><thead><tr><th scope="col">Office due date</th><th scope="col">Accepted on time</th><th scope="col">Due cohort</th><th scope="col">Rate</th></tr></thead><tbody>{items.map(item => <tr key={item.date}><th scope="row">{item.date}</th><td>{item.numerator}</td><td>{item.denominator}</td><td>{item.value === null ? 'Unknown' : `${item.value.toLocaleString('en-IN', { maximumFractionDigits: 1 })}%`}</td></tr>)}</tbody></table> : <p>No original due-date cohort is recorded for this period.</p>;
}
export function AnalyticsSummary({ data, onRecords }: { data: WorkSummary; onRecords: (metric: WorkMetric) => void }) {
    return <section className={styles.section} aria-label="Work metrics"><div className={styles.heading}><div><h3>Delivery and review metrics</h3><p>{data.from} – {data.to}, inclusive office dates · {data.officeZone}</p></div><span className={styles.tag}>{data.metricVersion}</span></div>
        <p className={styles.note}>Scope: {data.scope.toLowerCase()}. Generated {new Date(data.generatedAt).toLocaleString('en-IN')}. These are current measurements of retained facts; records and exports recheck current access and may have a newer generation.</p>
        <div className={styles.metricGrid}>{data.cards.map(card => <article className={styles.card} key={card.id} aria-label={`${card.id} ${card.title}`}><div className={styles.heading}><span className={styles.eyebrow}>{card.id}</span>{card.smallSample && <span className={styles.tag}>Small sample</span>}</div><h4>{card.title}</h4><strong className={styles.metricValue}>{metricValue(card)}</strong>
            <p>{card.definition}</p>{card.reason && <p className={styles.unavailable}>{card.reason}</p>}<dl className={styles.metricFacts}><div><dt>Observed sample</dt><dd>{card.sampleCount}</dd></div><div><dt>Known coverage</dt><dd>{card.coverageKnown} / {card.coverageTotal}</dd></div><div><dt>Excluded</dt><dd>{card.excluded}</dd></div>{card.numerator !== null && card.denominator !== null && <div><dt>Numerator / denominator</dt><dd>{card.numerator} / {card.denominator}</dd></div>}</dl>
            <button type="button" className="button button-secondary" aria-haspopup="dialog" onClick={() => onRecords(card)}>View {card.id} records</button></article>)}</div>
        <section className={styles.section} aria-label="Stage latency distributions"><h3>Stage latency and unresolved work</h3><p>Resolved observations measure elapsed seconds. Unresolved counts and age describe waiting work separately. Missing legacy milestones remain unknown.</p><div className={styles.memberGrid}>{data.stages.map(stage => <article className={styles.card} key={stage.stage}><h4>{stage.stage.replaceAll('_', ' ').toLowerCase()}</h4><dl className={styles.memberFacts}><div><dt>Observed sample</dt><dd>{stage.sampleCount}</dd></div><div><dt>Median</dt><dd>{durationLabel(stage.medianSeconds)}</dd></div><div><dt>p95</dt><dd>{durationLabel(stage.p95Seconds)}</dd></div><div><dt>Unresolved</dt><dd>{stage.unresolved}</dd></div><div><dt>Oldest unresolved</dt><dd>{durationLabel(stage.oldestUnresolvedSeconds)}</dd></div><div><dt>Known coverage</dt><dd>{stage.coverageKnown} / {stage.coverageTotal}</dd></div></dl></article>)}</div>{data.stages.length === 0 && <p>No retained stage observations are available.</p>}</section>
        <section className={styles.section} aria-label="Original commitment trends"><h3>Original commitment trends</h3><p>WORK07 groups tasks by their immutable original office due date. Current valid delivery acceptance must be on time. Unfinished or late tasks stay in the due denominator; final CEO closure is a separate measure.</p><details><summary>Daily original commitment trend ({data.trend.length} office dates)</summary><TrendRows items={data.trend} /></details>
            {data.departmentTrends.map(department => <details key={department.departmentId}><summary>{department.departmentName} original commitment trend</summary><TrendRows items={department.trend} /></details>)}{data.departmentTrends.length === 0 && <p className={styles.note}>No additional department trend is returned in this scope.</p>}</section>
    </section>;
}
