'use client';
import { Download } from 'lucide-react';
import { WorkDialog } from '../../workboard/components/work-dialog';
import type { AnalyticsState, WorkAnalyticsSession } from '../planning-session';
import styles from '../planning.module.css';
export function MetricRecords({ state, session }: { state: AnalyticsState; session: WorkAnalyticsSession }) {
    const view = state.records; if (!view || !state.applied || !state.summary) return null;
    const loading = state.busy.includes('records'), exporting = state.busy.includes('export'), data = view.data;
    const download = async () => { const result = await session.exportRecords(); if (!result) return; const url = URL.createObjectURL(result.blob), anchor = document.createElement('a'); anchor.href = url; anchor.download = result.filename; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); };
    return <WorkDialog titleId="work-metric-records-title" className={`work-create-dialog ${styles.dialog}`} onClose={() => session.closeRecords()}><div className={styles.form}><header className={styles.heading}><div><span className={styles.eyebrow}>{view.metric.id} · {state.summary.metricVersion}</span><h2 id="work-metric-records-title">{view.metric.title} records</h2></div><button type="button" className="button button-secondary" data-initial-focus onClick={() => session.closeRecords()}>Close metric records</button></header>
        <p>{state.applied.from} – {state.applied.to}, inclusive · {state.summary.officeZone} · {state.summary.scope.toLowerCase()} scope</p><p>{view.metric.definition}</p><p className={styles.note}>{data ? `Records generated ${new Date(data.generatedAt).toLocaleString('en-IN')}.` : 'Current records are loading.'} Current access is checked again. Distribution records describe stage observations rather than a count of distinct worksheets.</p>
        {state.recordsError && <div role="alert" className={styles.error}>{state.recordsError}<p>Reload this record view, or close it and apply the metric period again if the scope or metric definition changed.</p></div>}
        <div className={styles.actions}><button type="button" className="button button-secondary" disabled={loading || exporting} onClick={() => void session.loadRecords()}>Reload metric records</button><button type="button" className="button button-primary" disabled={!data || loading || exporting} onClick={() => void download()}><Download size={16} />{exporting ? 'Preparing export…' : `Export ${view.metric.id} CSV`}</button></div><p className={styles.note}>Export uses this metric version, date range and department filter. The server bounds exports to 5,000 authorized observations and rejects larger exports.</p>
        {loading && <p role="status">Loading authorized metric records…</p>}{data && <><div className={styles.recordList}>{data.items.map((record, index) => <article className={styles.card} key={`${record.id}:${record.occurredAt}:${index}`}><h3>{record.title}</h3><p>{record.assigneeName} · {record.departmentName}</p><dl className={styles.memberFacts}><div><dt>Current status</dt><dd>{record.status.replaceAll('_', ' ').toLowerCase()}</dd></div><div><dt>Original due date</dt><dd>{record.originalDueDate ?? 'Unknown'}</dd></div><div><dt>Current due date</dt><dd>{record.dueDate}</dd></div><div><dt>Observation</dt><dd>{record.occurredAt ? new Date(record.occurredAt).toLocaleString('en-IN') : 'No retained timestamp'}</dd></div></dl><p>{record.detail}</p></article>)}</div>{data.items.length === 0 && <p className={styles.empty}>No authorized observations match this metric and period.</p>}
            <nav className={styles.pagination} aria-label="Metric record pagination"><span>{data.totalElements} authorized observations · Page {view.page + 1} of {Math.max(1, data.totalPages)}</span><button type="button" className="button button-secondary" disabled={loading || exporting || view.page === 0} onClick={() => void session.loadRecords(view.page - 1)}>Previous metric page</button><button type="button" className="button button-secondary" disabled={loading || exporting || view.page + 1 >= data.totalPages} onClick={() => void session.loadRecords(view.page + 1)}>Next metric page</button></nav></>}
    </div></WorkDialog>;
}
