'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowRightLeft } from 'lucide-react';
import { isBackendConfigured } from '../../../lib/api-client';
import { WorkDialog } from '../../workboard/components/work-dialog';
import { useHandoverSession } from '../use-planning-session';
import { validateHandover } from '../planning-model';
import styles from '../planning.module.css';
export function TaskHandover({ taskId, onChanged }: { taskId: string; onChanged: () => void }) {
    const { state, session } = useHandoverSession(taskId); const initialSession = useRef(session), returnFocus = useRef<HTMLElement | null>(null);
    const [discard, setDiscard] = useState<string | null>(null);
    useEffect(() => { if (session !== initialSession.current || !isBackendConfigured) return; void session.load(); }, [session]);
    useEffect(() => { returnFocus.current = null; }, [session.identityKey]);
    useEffect(() => { if (state.draft || state.busy) return; if (returnFocus.current?.isConnected) returnFocus.current.focus({ preventScroll: true }); returnFocus.current = null; }, [state.draft, state.busy]);
    const view = state.view, draft = state.draft;
    const close = () => { if (state.busy || state.uncertain) return; if (draft?.reason || draft?.targetEmployeeId) setDiscard(session.identityKey); else session.closeDraft(); };
    return <section className={styles.handover} aria-label="Worksheet handover"><div className={styles.heading}><div><h3>Assignment handover</h3><p>Move current delivery responsibility within the authorized department.</p></div><button type="button" className="button button-secondary" disabled={state.busy || !isBackendConfigured} onClick={() => void session.load()}>Reload assignment & handover history</button></div>
        {!isBackendConfigured && <p>Connect the secure backend to read current assignment history.</p>}{state.error && !draft && <div className={styles.error} role="alert">{state.error}</div>}{state.busy && <p role="status">Checking the current assignment…</p>}{state.notice && !draft && <p className={styles.notice} role="status">{state.notice}</p>}
        {view && <><dl className={styles.memberFacts}><div><dt>Current assignee</dt><dd>{view.currentAssigneeName}</dd></div><div><dt>Original assignee</dt><dd>{view.originalAssigneeName}</dd></div><div><dt>Current worksheet version</dt><dd>{view.taskVersion}</dd></div></dl><p className={styles.note}>The original assignee and original commitment stay unchanged. Previous text, checklist and private evidence retain their authors. Submitted or accepted delivery is revised: current acceptance is cleared and the new assignee must submit their own delivery.</p>
            {view.canHandover ? <button type="button" className="button button-primary" disabled={state.busy} aria-haspopup="dialog" onClick={() => { returnFocus.current = document.activeElement as HTMLElement | null; session.openDraft(); }}><ArrowRightLeft size={16} />Handover worksheet</button> : <p className={styles.callout}>{view.unavailableReason ?? 'Your current account can read retained handover history.'}</p>}
            <section aria-label="Retained handover history"><h3>Retained handover history</h3>{view.history.length === 0 ? <p>No handover has been recorded for this worksheet.</p> : <ol className={styles.history}>{view.history.map(item => <li key={item.id}><strong>{item.fromName} → {item.toName}</strong><p>{item.reason}</p><p className={styles.note}>By {item.actorName} · effective {new Date(item.effectiveAt).toLocaleString('en-IN')} · recorded {new Date(item.occurredAt).toLocaleString('en-IN')}</p><p className={styles.note}>Assignment revision {item.assignmentRevision} · previous submission {item.previousSubmissionVersion === null ? 'not recorded' : `version ${item.previousSubmissionVersion}`}</p></li>)}</ol>}{view.historyTruncated && <p role="status">Showing the latest retained handovers; older events are retained by the server.</p>}</section>
        </>}
        {draft && view && <WorkDialog className={`work-create-dialog ${styles.dialog}`} titleId="handover-form-title" onClose={close}><form className={styles.form} onSubmit={async event => { event.preventDefault(); if (await session.save()) onChanged(); }}><header className={styles.heading}><div><span className={styles.eyebrow}>CONTROLLED HANDOVER</span><h2 id="handover-form-title">Handover worksheet</h2></div><button type="button" className="button button-secondary" disabled={state.busy || state.uncertain} onClick={close}>Close handover form</button></header>
            <div className={styles.callout}><strong>Current: {view.currentAssigneeName} · version {view.taskVersion}</strong><p>Original: {view.originalAssigneeName}. Handover takes effect immediately when saved. Current eligibility, leave and worksheet state are checked again by the server.</p></div>
            {state.error && <div className={styles.error} role="alert">{state.error}</div>}{state.conflict && <p className={styles.error}>This worksheet changed. Your assignee and reason are retained. Reload the current assignment and review its version before saving again.</p>}{state.uncertain && <p className={styles.error}>The response did not confirm whether handover was saved. Fields are locked. Reload the assignment and review the retained history before another action.</p>}
            {(state.conflict || state.uncertain) && <button type="button" className="button button-secondary" disabled={state.busy} onClick={() => void session.load()}>Reload assignment and retain handover fields</button>}{state.notice && <p className={styles.notice} role="status">{state.notice}</p>}
            <label>New department assignee<select aria-label="New department assignee" data-initial-focus required disabled={state.busy || state.uncertain} value={draft.targetEmployeeId} onChange={event => session.changeDraft({ ...draft, targetEmployeeId: event.target.value })}><option value="">Choose a current eligible assignee</option>{draft.targetEmployeeId && !view.eligibleAssignees.some(person => person.employeeId === draft.targetEmployeeId) && <option value={draft.targetEmployeeId} disabled>Retained selection · currently unavailable</option>}{view.eligibleAssignees.filter(person => person.employeeId !== view.currentEmployeeId).map(person => <option key={person.employeeId} value={person.employeeId}>{person.displayName} · {person.role.replaceAll('_', ' ').toLowerCase()}</option>)}</select></label>
            <label>Handover reason<textarea aria-label="Handover reason" rows={4} minLength={5} maxLength={1000} required disabled={state.busy || state.uncertain} value={draft.reason} onChange={event => session.changeDraft({ ...draft, reason: event.target.value })} /></label><p className={styles.note}>{draft.reason.length}/1,000 characters. Prior submissions and decisions remain in retained history. This changes delivery assignment; reviewer delegation is managed separately.</p>
            {state.reviewRequired && <button type="button" className="button button-secondary" onClick={() => session.acknowledgeCurrent()}>I reviewed the current assignment and history</button>}
            {state.busy && <p role="status">Saving or verifying current handover…</p>}<div className={styles.actions}><button type="button" className="button button-secondary" disabled={state.busy || state.uncertain} onClick={close}>Cancel handover</button><button type="submit" className="button button-primary" disabled={state.busy || state.conflict || state.uncertain || state.reviewRequired || Boolean(validateHandover(view, draft.targetEmployeeId, draft.reason))}>{state.busy ? 'Checking handover…' : 'Confirm immediate handover'}</button></div>
        </form></WorkDialog>}
        {discard === session.identityKey && draft && <WorkDialog className={`work-create-dialog ${styles.dialog}`} titleId="handover-discard-title" onClose={() => setDiscard(null)}><div className={styles.form}><h2 id="handover-discard-title">Keep unsaved handover fields?</h2><p>This handover form has not been saved.</p><div className={styles.actions}><button type="button" className="button button-primary" data-initial-focus onClick={() => setDiscard(null)}>Keep editing handover</button><button type="button" className="button button-secondary" onClick={() => { session.closeDraft(); setDiscard(null); }}>Discard handover form</button></div></div></WorkDialog>}
    </section>;
}
