import type { Workload } from '../types';
import styles from '../planning.module.css';
const readable = (value: string) => value.replaceAll('_', ' ').toLowerCase();
export function WorkloadPanel({ data }: { data: Workload }) {
    return <section className={styles.section} aria-label="Current department workload"><div className={styles.heading}><div><h3>Current workload</h3><p>{data.departmentName ?? 'Authorized department'} · office date {data.officeDate} · {data.officeZone}</p></div><span className={styles.tag}>Current assignments</span></div>
        <p className={styles.note}>Generated {new Date(data.generatedAt).toLocaleString('en-IN')}. Counts describe current delivery and review work. Member order is neutral; these are assignment facts.</p>
        <dl className={styles.facts}><div><dt>Active assignments</dt><dd>{data.totals.activeTasks}</dd></div><div><dt>Due today / upcoming</dt><dd>{data.totals.dueToday} / {data.totals.upcoming}</dd></div><div><dt>Overdue delivery</dt><dd>{data.totals.overdueDelivery}</dd></div><div><dt>Pending review / blocked</dt><dd>{data.totals.pendingReview} / {data.totals.blocked}</dd></div></dl>
        <div className={styles.callout}><strong>Effort and capacity</strong><p>{data.totals.estimatedMinutes === null ? 'Estimated effort is unknown.' : `${data.totals.estimatedMinutes.toLocaleString('en-IN')} known estimated minutes across ${data.totals.estimatedTasks} tasks.`} {data.totals.unestimatedTasks} tasks have no estimate. {data.totals.capacityMinutes == null ? 'Capacity is unknown: maintained capacity input is unavailable.' : `Recorded capacity: ${data.totals.capacityMinutes} minutes.`}</p><p>Counts, partial estimates and availability support assignment decisions. Missing estimates are excluded from known effort.</p></div>
        {data.members.length === 0 ? <p className={styles.empty}>No retained assignments or eligible members are available in this scope.</p> : <div className={styles.memberGrid}>{data.members.map(member => <article className={styles.card} key={member.employeeId} aria-label={`Workload for ${member.name}`}><div className={styles.heading}><h4>{member.name}</h4><span className={styles.tag}>{readable(member.role)}</span></div>
            <p className={member.eligible ? styles.note : styles.unavailable}>{member.eligible ? 'Currently eligible for assignment' : 'Unavailable for new assignment'}{member.unavailableReasons.length > 0 && ` · ${member.unavailableReasons.map(readable).join('; ')}`}</p>
            <dl className={styles.memberFacts}><div><dt>Active</dt><dd>{member.activeTasks}</dd></div><div><dt>Due today</dt><dd>{member.dueToday}</dd></div><div><dt>Upcoming</dt><dd>{member.upcoming}</dd></div><div><dt>Overdue delivery</dt><dd>{member.overdueDelivery}</dd></div><div><dt>Pending review</dt><dd>{member.pendingReview}</dd></div><div><dt>Blocked</dt><dd>{member.blocked}</dd></div></dl>
            <p>{member.estimatedMinutes === null ? 'Effort unknown' : `${member.estimatedMinutes.toLocaleString('en-IN')} known estimated minutes`} · {member.estimatedTasks} estimated / {member.unestimatedTasks} unestimated tasks.</p><p className={styles.note}>{member.capacityMinutes === null ? 'Capacity unknown' : `${member.capacityMinutes} recorded capacity minutes`}{!member.eligible && member.activeTasks > 0 ? ' · Existing assignments are retained and need an authorized handover decision.' : ''}</p>
        </article>)}</div>}
    </section>;
}
