"use client";
import { useState } from "react";
import { X } from "lucide-react";
import type { WorkboardAction, WorkboardDetail, WorkboardItem } from "../types/workboard";
import { WorkPlanningPanel } from "./work-planning";
import { WorkDialog } from "./work-dialog";
import { WorkTaskPill } from "./work-task-pill";
import { workTaskStatusLabel } from "../utils/work-utils";
import { workActorName } from "../utils/workboard-model";

export const actionLabels: Record<WorkboardAction, string> = { start: "Start", complete: "Complete", approve: "Approve delivery", "request-changes": "Request changes", acknowledge: "Acknowledge", "insight-rework": "Create rework plan", "revise-rework": "Update & resubmit", "hr-rework": "Return for rework", "hr-audit": "Audit & send to Manager", "open-oversight": "Open work oversight" };
export function WorkTaskActions({ task, busy, onAction }: { task: WorkboardItem; busy: boolean; onAction: (task: WorkboardItem, action: WorkboardAction) => void }) {
    return <div className="work-task-actions">{task.allowedActions.map((action) => <button key={action} type="button" className={`button ${["approve", "hr-audit", "acknowledge"].includes(action) ? "button-approve" : ["request-changes", "hr-rework"].includes(action) ? "button-reject" : "button-secondary"}`} disabled={busy} onClick={() => onAction(task, action)}>{action === "start" && (task.teamLeadReview || task.insightReviewReason) ? "Start rework" : action === "complete" && (task.teamLeadReview || task.insightReviewReason) ? "Submit corrected work" : action === "insight-rework" && task.assigneeRole === "TEAM_LEAD" ? "Start rework" : actionLabels[action]}</button>)}</div>;
}
export function WorkTaskDrawer({ id, detail, error, busy, onClose, onReload, onAction, stageLabel }: { id: string; detail: WorkboardDetail | null; error: string; busy: boolean; onClose: () => void; onReload: () => void; onAction: (task: WorkboardItem, action: WorkboardAction) => void; stageLabel: (task: WorkboardItem) => string }) {
    const [tab, setTab] = useState("Overview");
    const task = detail?.item;
    return <WorkDialog className="work-drawer" titleId="work-drawer-title" onClose={onClose}>
        <header className="work-drawer-header"><div><small>WORKSHEET · #{id.slice(-8).toUpperCase()}</small><h2 id="work-drawer-title">{task?.title ?? "Worksheet details"}</h2>{task && <WorkTaskPill status={task.status} label={stageLabel(task)} />}</div><button className="icon-button" type="button" aria-label="Close worksheet details" onClick={onClose} autoFocus><X size={20} /></button></header>
        {error && <div className="login-error" role="alert">{error}<button type="button" className="button button-secondary" onClick={onReload}>Reload worksheet</button></div>}{!task && !error && <p role="status">Loading current worksheet details…</p>}
        {task && <><div className="work-drawer-tabs" role="tablist" aria-label="Worksheet details">{["Overview", "Updates", "Review history", "Planning & evidence"].map((name, index, tabs) => <button key={name} type="button" role="tab" id={`worksheet-tab-${index}`} aria-selected={tab === name} aria-controls="worksheet-tab-panel" tabIndex={tab === name ? 0 : -1} onClick={() => setTab(name)} onKeyDown={(event) => { if (!["ArrowRight", "ArrowLeft", "Home", "End"].includes(event.key)) return; event.preventDefault(); const target = event.key === "Home" ? 0 : event.key === "End" ? 3 : (index + (event.key === "ArrowRight" ? 1 : 3)) % 4; setTab(tabs[target]); document.getElementById(`worksheet-tab-${target}`)?.focus(); }}>{name}</button>)}</div>
            <div className="work-drawer-body" id="worksheet-tab-panel" role="tabpanel" aria-labelledby={`worksheet-tab-${["Overview", "Updates", "Review history", "Planning & evidence"].indexOf(tab)}`} tabIndex={0}>
                {tab === "Overview" && <><section className="task-sheet-brief" aria-label="Full work instructions"><h3>Full instructions</h3><p>{task.description}</p></section><dl className="work-detail-fields">
                    <div><dt>Assigned to</dt><dd>{task.assigneeName} · {task.assigneeRole === "TEAM_LEAD" ? "Team Lead" : "Employee"}</dd></div><div><dt>Department / branch</dt><dd>{task.departmentBranch}</dd></div><div><dt>Due date</dt><dd>{task.dueDate}</dd></div><div><dt>Assigned by</dt><dd>{task.assignedByRole === "HR_ADMIN" ? "HR Admin" : "Team Lead"}</dd></div>
                    <div><dt>Delivery stage</dt><dd>{workTaskStatusLabel(task.status)}{task.status === "COMPLETED" ? " · Submitted for review" : ""}</dd></div><div><dt>Review stage</dt><dd>{task.auditStatus === "NOT_AUDITED" ? "Not audited" : task.auditStatus.replaceAll("_", " ").toLowerCase()}</dd></div><div><dt>Current submission version</dt><dd>{task.submissionVersion === null ? "Not recorded for this worksheet" : `Version ${task.submissionVersion}`}</dd></div><div><dt>Next actor</dt><dd>{task.nextActor ? workActorName(task.nextActor) : "No further review required"}</dd></div></dl><p className="work-detail-note">Delivery approval and final CEO closure are separate stages. Submission versions describe the current text submission.</p>{(task.insightReviewReason || task.teamLeadReview) && <section className="insight-rework-card"><h3>Current reviewer feedback</h3><p>{task.insightReviewReason ?? task.teamLeadReview}</p></section>}</>}
                <div hidden={tab !== "Planning & evidence"}><WorkPlanningPanel task={task} onChanged={onReload} /></div>
                {tab === "Updates" && <div className="task-sheet-responses"><section><h3>{task.assigneeRole === "TEAM_LEAD" ? "Team Lead work update" : "Employee work update"}</h3><p>{task.employeeUpdate ?? "No work update has been submitted."}</p></section><section><h3>Team Lead decision</h3><p>{task.teamLeadReview ?? "No delivery decision has been recorded."}</p></section>{task.insightReviewReason && <section><h3>{task.insightReviewSource?.replaceAll("_", " ") ?? "Reviewer"} feedback</h3><p>{task.insightReviewReason}</p></section>}</div>}
                {tab === "Review history" && <><p className="work-detail-note">Recorded events and stored milestones only. Earlier submission cycles may not have retained evidence.</p><ol className="work-history">{detail.history.map((event) => <li key={event.id}><strong>{event.title}</strong><time dateTime={event.occurredAt}>{new Date(event.occurredAt).toLocaleString("en-IN")}</time>{event.actorRole && <small>{event.actorRole.replaceAll("_", " ")}</small>}{event.note && <p>{event.note}</p>}</li>)}</ol>{detail.history.length === 0 && <p>No retained review events are available.</p>}{detail.historyTruncated && <p role="status">Showing the latest 200 retained events.</p>}</>}
            </div><footer className="work-drawer-footer"><WorkTaskActions task={task} busy={busy || Boolean(error)} onAction={onAction} />{task.allowedActions.length === 0 && <p>No action is required from your current account.</p>}</footer></>}
    </WorkDialog>;
}
