'use client';
import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react';
import { ApiError, apiRequest } from '../../lib/api-client';
import { officeToday, formatOfficeTime, type AvailableSlot, type PublicHost } from '../../lib/appointments';
import { useAdminSession } from '../integrations/use-admin-session';
import { kioskApi } from './api/kiosk-api';
import type { Group, GroupRequest } from './types';
import styles from './kiosk.module.css';

export function GroupRegistration() {
  const [groups,setGroups]=useState<Group[]>([]),[hosts,setHosts]=useState<PublicHost[]>([]),[slots,setSlots]=useState<AvailableSlot[]>([]);
  const [type,setType]=useState('HR_VISIT'),[host,setHost]=useState(''),[date,setDate]=useState(officeToday),[slot,setSlot]=useState('');
  const [label,setLabel]=useState(''),[purpose,setPurpose]=useState(''),[members,setMembers]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[hasPending,setHasPending]=useState(false);
  const pending=useRef<GroupRequest|null>(null);
  const {begin,busy,sessionEnded}=useAdminSession(()=>{pending.current=null;setHasPending(false);setGroups([]);setHosts([]);setSlots([]);setMembers('');setLabel('');setPurpose('');setHost('');setSlot('');setError('');setMessage('');});
  const eligible=hosts.filter(value=>type==='CLIENT_MEETING'?value.category==='TEAM_LEAD':value.category==='HR');
  const load=useCallback(async()=>{const op=begin();if(!op)return;setError('');try{const [directory,data]=await Promise.all([apiRequest<PublicHost[]>('/public/hosts',{signal:op.signal,cache:'no-store'}),kioskApi.groups(op.signal)]);if(op.current()){setHosts(directory);setGroups(data);}}catch{if(op.current())setError('Groups and hosts could not be loaded. Reload before submitting.');}finally{op.finish();}},[begin]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer);},[load]);
  useEffect(()=>{if(!host||!date||sessionEnded)return;const controller=new AbortController();let active=true;const timer=setTimeout(()=>{setSlots([]);setSlot('');void apiRequest<AvailableSlot[]>(`/public/hosts/${encodeURIComponent(host)}/available-slots?date=${encodeURIComponent(date)}&type=${type}`,{signal:controller.signal,cache:'no-store'}).then(data=>{if(active){setSlots(data);setSlot(data[0]?.start??'');}}).catch(()=>{if(active)setError('Available times could not be loaded. Choose the host and date again.');});},0);return()=>{active=false;controller.abort();clearTimeout(timer);};},[host,date,type,sessionEnded]);
  const submit=async(event:FormEvent)=>{event.preventDefault();const op=begin();if(!op)return;setError('');setMessage('');try{
    if(!pending.current){const selected=slots.find(value=>value.start===slot),selectedHost=hosts.find(value=>value.id===host);if(!selected||!selectedHost)throw new Error('Choose an available host and time.');
      const rows=members.trim().split(/\r?\n/).map(line=>{const parts=line.split('|').map(part=>part.trim());if(parts.length<3||parts.length>4)throw new Error('Use name | email | phone | company for each visitor.');const [visitorName,visitorEmail,visitorPhone,visitorCompany='']=parts;if(!visitorName||visitorName.length>170||!/^\S+@\S+\.\S+$/.test(visitorEmail)||visitorEmail.length>180||!visitorPhone||visitorPhone.length>30||visitorCompany.length>160)throw new Error('Check each visitor’s name, email, phone and company.');return {visitorName,visitorEmail,visitorPhone,visitorCompany};});
      if(rows.length<2||rows.length>50||new Set(rows.map(row=>row.visitorEmail.toLowerCase())).size!==rows.length)throw new Error('Enter 2–50 visitors with different email addresses.');
      pending.current={requestId:crypto.randomUUID(),label:label.trim(),type,hostEmployeeId:host,routingDepartmentId:selectedHost.departmentId,slotStart:selected.start,slotEnd:selected.end,purpose:purpose.trim(),members:rows};setHasPending(true);
    }
    const result=await kioskApi.register(pending.current,op.signal);if(!op.current())return;
    pending.current=null;setHasPending(false);setMembers('');setLabel('');setPurpose('');setGroups(values=>[result,...values.filter(value=>value.id!==result.id)].slice(0,20));setMessage(`${result.members.length} visitors registered. Each still needs Security, Reception and the required approvals.`);
  }catch(reason){if(op.current()){if(reason instanceof ApiError && ([400,403,422].includes(reason.status) || reason.problem.errorCode==='SLOT_ALREADY_BOOKED')){pending.current=null;setHasPending(false);if(reason.problem.errorCode==='SLOT_ALREADY_BOOKED')setSlot('');}setError(pending.current?'Registration was not confirmed. Retry the same request; its contents remain locked to prevent duplicates.':reason instanceof Error?reason.message:'Check the group details.');}}finally{op.finish();}};
  return <section className={styles.panel} aria-label="Group preregistration"><h2>Preregister a group</h2><p>One host and time, with a separate approval and access record for every visitor.</p><button className="button button-secondary" disabled={busy||sessionEnded} onClick={()=>void load()}>Reload groups</button><form className={styles.form} onSubmit={submit}><fieldset disabled={busy||sessionEnded||hasPending} className={styles.form}><label>Group label<input value={label} onChange={e=>setLabel(e.target.value)} maxLength={120} required/></label><div className={styles.columns}><label>Group visit type<select value={type} onChange={e=>{setType(e.target.value);setHost('');setSlots([]);setSlot('');}}><option value="HR_VISIT">HR visit</option><option value="INTERVIEW">Interview</option><option value="CLIENT_MEETING">Client meeting</option></select></label><label>Group host<select value={host} onChange={e=>setHost(e.target.value)} required><option value="">Select host</option>{eligible.map(value=><option key={value.id} value={value.id}>{value.displayName}</option>)}</select></label><label>Group date<input type="date" value={date} min={officeToday()} onChange={e=>{setDate(e.target.value);setSlots([]);setSlot('');}} required/></label><label>Group time<select value={slot} onChange={e=>setSlot(e.target.value)} required><option value="">Select available time</option>{slots.map(value=><option key={value.start} value={value.start}>{formatOfficeTime(value.start)}</option>)}</select></label></div><label>Group purpose<input value={purpose} onChange={e=>setPurpose(e.target.value)} maxLength={1000} required/></label><label>Group visitors<textarea value={members} onChange={e=>setMembers(e.target.value)} maxLength={27500} required aria-describedby="group-format"/></label><small id="group-format">One visitor per line: name | email | phone | company. Enter 2–50 visitors.</small></fieldset><button className="button button-primary" disabled={busy||sessionEnded||(!hasPending&&!slot)}>{hasPending?'Retry same group request':'Register group'}</button></form>{message&&<p role="status">{message}</p>}{error&&<p role="alert" className={styles.error}>{error}</p>}<div className={styles.list}>{groups.map(value=><details key={value.id}><summary>{value.label} · {value.members.length} visitors</summary>{value.members.map(member=><p key={member.appointmentId}>{member.referenceNumber} · {member.status.replaceAll('_',' ')}</p>)}</details>)}</div></section>;
}
