"use client";

import { useModalDialog } from "../../shared/hooks/use-modal-dialog";
import { FileClock, LockKeyhole, MessageSquare, QrCode, ShieldCheck, X } from "lucide-react";

export function PrivacyCentreModal({ onClose }: { onClose: () => void }) {
    useModalDialog(onClose);
    return <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}>
        <section className="modal glass-panel privacy-centre-modal" role="dialog" aria-modal="true" aria-labelledby="privacy-centre-title">
            <header><div><span>PRIVACY CENTRE</span><h2 id="privacy-centre-title">How BrainServe Connect protects visitor data</h2><p>Operational privacy controls enforced across appointments, QR passes and access records.</p></div><button className="icon-button" onClick={onClose} aria-label="Close privacy centre"><X size={19} /></button></header>
            <div className="privacy-centre-content">
                <article><ShieldCheck size={20} /><span><strong>Purpose-limited collection</strong><small>Visitor identity and contact details are collected only to coordinate, approve and secure the requested visit.</small></span></article>
                <article><LockKeyhole size={20} /><span><strong>Role-scoped access</strong><small>Signed-in roles are locked server-side. Reception, HR, CEO and Security only see actions authorized for their duties.</small></span></article>
                <article><QrCode size={20} /><span><strong>Signed, expiring visitor passes</strong><small>QR content is generated by the backend, signed against tampering and checked against appointment status and validity.</small></span></article>
                <article><FileClock size={20} /><span><strong>Audited retention</strong><small>Privileged changes are recorded, while retention and active consent versions are controlled from workspace settings.</small></span></article>
                <div className="privacy-contact"><MessageSquare size={18} /><span><strong>Questions or a privacy request?</strong><small>Contact the company support address configured in Company profile.</small></span></div>
            </div>
            <footer className="privacy-centre-actions"><button className="button button-primary" onClick={onClose}>I understand</button></footer>
        </section>
    </div>;
}

