package com.brainserve.appointment.appointment.domain;

public enum AppointmentStatus {
    DRAFT, PENDING_VERIFICATION, PENDING_SECURITY_INTAKE, PENDING_RECEPTION_VERIFICATION,
    PENDING_APPROVAL, PENDING_HR_APPROVAL, PENDING_TEAM_LEAD_APPROVAL,
    PENDING_MANAGER_APPROVAL, PENDING_CEO_APPROVAL,
    APPROVED, REJECTED,
    RESCHEDULE_REQUESTED, RESCHEDULED, CANCELLED, CHECKED_IN, IN_MEETING,
    CHECKED_OUT, COMPLETED, NO_SHOW, EXPIRED
}
