package com.brainserve.appointment.iam.domain;

public enum Permission {
    EMPLOYEE_CREATE, EMPLOYEE_READ, EMPLOYEE_UPDATE, EMPLOYEE_STATUS_CHANGE,
    EMPLOYEE_DOCUMENT_READ, EMPLOYEE_DOCUMENT_WRITE,
    SALARY_READ, SALARY_WRITE, SALARY_APPROVE,
    DEPARTMENT_MANAGE, DESIGNATION_MANAGE, ROLE_MANAGE,
    APPOINTMENT_REQUEST, APPOINTMENT_APPROVE, APPOINTMENT_REJECT, APPOINTMENT_RESCHEDULE,
    HR_VISIT_APPROVE, TEAM_LEAD_VISIT_APPROVE, TEAM_LEAD_ASSIGNMENT_MANAGE, TEAM_LEAD_DIRECTORY_VIEW,
    MANAGER_VISIT_APPROVE, MANAGER_ASSIGNMENT_MANAGE,
    CEO_VISIT_APPROVE, STAFF_ACCOUNT_MANAGE, STAFF_ACCOUNT_APPROVE,
    VISITOR_REGISTER, VISITOR_VERIFY, SECURITY_VISITOR_INTAKE, RECEPTION_VISIT_VERIFY,
    VISITOR_CHECK_IN, VISITOR_CHECK_OUT, VISITOR_OCCUPANCY_READ,
    QR_PASS_VERIFY, COMPANY_PROFILE_MANAGE, APPOINTMENT_POLICY_MANAGE,
    NOTIFICATION_CONFIGURE, INTERNAL_NOTIFICATION_READ, INTERNAL_NOTIFICATION_SEND, PRIVACY_POLICY_MANAGE,
    LEAVE_REQUEST_CREATE, LEAVE_REQUEST_REVIEW, WORKFORCE_RECORD_VIEW, HR_ACCOUNT_DEACTIVATE,
    WORK_TASK_READ, WORK_TASK_CREATE, WORK_TASK_PROGRESS, WORK_TASK_REVIEW, WORK_TASK_PERFORMANCE_READ,
    WORK_INSIGHT_READ, WORK_INSIGHT_AUDIT, WORK_INSIGHT_MANAGER_APPROVE,
    WORK_INSIGHT_CEO_APPROVE, WORK_INSIGHT_ARCHIVE_READ,
    REPORT_VIEW, AUDIT_VIEW, SYSTEM_CONFIGURE
}
